### ISSUE TITLE
Check VMEC output quantities that rely on radial derivatives

### ISSUE THREAD

**Issue by ddudt** [PlasmaControl/DESC#103]
The NetCDF output quantities `bsubsmns`, `currumnc`, and `currvmnc` are not tested against VMEC results. These quantities should be functions of radial derivatives, and the finite differences in VMEC are expected to differ from the spectral derivatives in DESC. We need to confirm how these quantities are computed in VMEC and find appropriate alternatives tests to check the DESC outputs.

**Comment by ddudt** [comment]
Similarly, the output quantities `bsupumnc` and `bsubumnc` should not be directly compared because VMEC and DESC generally use different poloidal angles. The quantities are currently being tested by comparison to VMEC with crude tolerances.

**Comment by f0uriest** [comment]
@ddudt is it possible to add tests for these quantites to #262 ?
