### ISSUE TITLE
signed curvature

### ISSUE THREAD

**Issue by ddudt** [PlasmaControl/DESC#1039]
Our curvature compute quantities are always positive. It would be useful to define a signed curvature to distinguish between convex and concave shapes. This should be particularly easy to implement for the `FourierPlanarCurve` class. We could either: 

- Update the `FourierPlanarCurve` compute quantity to be the signed version, leaving all of the other curves with the positive version. Or
- Add a new compute quantity for "signed curvature" or something, which is not implemented for the other curve types (return `NaN`?)

**Comment by dpanici** [comment]
I think that having the quantity just for the `FourierPlanarCurve` makes sense, and then the Objective for it could just throw a `NotImplementedError` if any coil is passed in which is not a `FourierPlanarCurve`?

**Comment by dpanici** [comment]
Dot curvature vector with centroid to get signed curvature for every type
