### ISSUE TITLE
Clarify documentation

### ISSUE THREAD

**Issue by ddudt** [PlasmaControl/DESC#1087]
A running list of things to add or clarify in the documentation: 

- [ ] Structure/data type of compute data. For most `Optimizable` objects, `thing.compute` returns a dictionary of the computed quantities. But for an `OptimizableCollection` like a `CoilSet`, it returns a list of dictionaries. 
- [x] #1027 should explain that `basis` is a possible `kwarg` for compute and that default is `rpz` for every vector/tensor quantity
- [x] Show uses of some utility functions somewhere in the docs, or make them part of the public API https://github.com/PlasmaControl/DESC/issues/723

**Comment by dpanici** [comment]
#723

**Comment by dpanici** [comment]
Closing as the remaining point is mentioned in docstring of the related classes
