### ISSUE TITLE
Change description of \nabla\alpha

### ISSUE THREAD

**Issue by acerfon** [PlasmaControl/DESC#1100]
The description of \nabla\alpha in the list of variables documentation, https://desc-docs.readthedocs.io/en/stable/variables.html#desc-equilibrium-equilibrium-equilibrium, still is inaccurate:

1) \nabla\alpha does **not** point along the field lines, since \alpha is a field line label. \nabla\alpha is orthogonal to the field lines.

2) In my calculations in DESC, \nabla\alpha is **not** a unit vector.

**Comment by unalmis** [comment]
Thanks for catching this in #1031. It was resolved by pull request #1032. You can find the updated `latest` documentation [here](https://desc-docs.readthedocs.io/en/latest/variables.html). The link you provided is the `stable` documentation which will be replaced with `latest` once a new release of DESC is pushed from the `master` branch to PyPI (the place that stores the desc version installable via `pip install desc-opt`.

**Comment by dpanici** [comment]
We hope to get the new release out by Monday, apologies for the delay!

**Comment by acerfon** [comment]
Thank you guys, awesome - sorry for the redundancy!
