### ISSUE TITLE
Make Linear Objective to Constrain Sum of Coil Currents

### ISSUE THREAD

**Issue by dpanici** [PlasmaControl/DESC#1111]
Instead of using `ToroidalFlux` or fixing a single coil current to avoid the trivial solution of zero current in a stage two vacuum coil optimization, you can also calculate the line integral of the covariant zeta component of the field, which is related to the sum of coil currents through an amperean loop as

$$
\begin{align}
     \oint_{\partial A} \mathbf{B} \cdot d\mathbf{l}&= I_{pol}= \mu_0 \sum_{i=1}^{N_{coils}} I_{i}^{coil} N_i^{poloidal~ transits}\\
     &\text{$\mathbf{B} \cdot d\mathbf{l} = \mathbf{B}\cdot \frac{\partial \mathbf{r}}{\partial \zeta} d\zeta = B_{\zeta} d\zeta$, LHS becomes}\\
     \Aboxed{N_{FP}\int_{0}^{2\pi/N_{FP}} B_{\zeta}d\zeta &= \mu_0 \sum_{i=1}^{N_{coils}} I_{i}^{coil} N_i^{poloidal~transits}}
\end{align}
$$

Where $N_i^{poloidal~transits}$ is the number of poloidal transits a coil makes (this is one for modular coils and equal to the winding number for helical coils). This constraint and a good quadratic flux optimization ensures the coils exactly create the correct magnetic field magnitude. Of course this is not strictly needed for vacuum optimization but is a 3rd way of avoiding the trivial solution

**Comment by ddudt** [comment]
This functionality is already trivial to implement with `LinearObjectiveFromUser`, but we can still make a standalone objective for it since this is a common use case.

**Comment by dpanici** [comment]
Possibly subclass `FixParameters` and override compute method to be sum over the x[indices] = target instead of x[indices] = target
