### ISSUE TITLE
Issue reading axis from vmec input

### ISSUE THREAD

**Issue by f0uriest** [PlasmaControl/DESC#1120]
VMEC input files specify the axis geometry coeffs usually as 
`raxis_cc = ...`
`zaxis_cs = ...`

But some only use
`raxis = ...`
`zaxis = ...`

If it's the latter, we read it incorrectly and assign `zaxis` to `zaxis_cc`. It looks like the VMEC parser was designed to handle the latter case, but we need to swap CC and CS somewhere around https://github.com/PlasmaControl/DESC/blob/986f529ac12b67ec2e3e8029af41d5e5eb363b7d/desc/input_reader.py#L1337

**Comment by dpanici** [comment]
remove paranth from CC and add to CS for zaxis
