### ISSUE TITLE
Decide on how to deal with `_compute_position` default grid for `MixedCoilSet`

### ISSUE THREAD

**Issue by dpanici** [PlasmaControl/DESC#1123]
Compute position default grid for mixed coilset, right now we throw an error if `None` is passed into `MixedCoilSet._compute_position` as it is hard to do the computation when the grids dont all have the same number of nodes. We can either keep it this way, or maybe add a logical which
- does efficient way for CoilSet, or if it is a MixedCoilSet but a grid is passed in,  or
- if grid is none and it is a MixedCoilSet, then use logic from _Coil_Objective to compute based on default grid and then rotate/reflect individually the positions, then figure out a way to compute the distance matrix with the ragged arrays (this might be more work then it is worth though)

If we don't want to implement we can close this, just wanted to leave this here for now

**Comment by f0uriest** [comment]
I think just using a single default grid with a reasonably high resolution is probably fine for 99% of cases. Dealing with ragged arrays is super annoying, and position/distance is a super cheap calculation so we can use high resolution without much cost.

**Comment by dpanici** [comment]
Resolved by #1109
