### ISSUE TITLE
kinetic profiles from pressure profile

### ISSUE THREAD

**Issue by ddudt** [PlasmaControl/DESC#1129]
If the user inputs kinetic profiles we can calculate the pressure from the density and temperature. But if the user inputs the pressure profile instead, the kinetic profiles are presently set to NaN. It might be better to introduce a new optimizable parameter that sets the density and temperature from the pressure. A simple example with a scalar parameter $\alpha \in (0,1)$: $n = p^\alpha$, $T = p^{1-\alpha}$

This would be useful for optimizing kinetic profiles while keeping the pressure profile constant. Otherwise this would require adding logic for constraints between multiple `Optimizable` "things", and those constraints between the density and temperature will generally not be linear. It could also already be accomplished by setting a target pressure in the optimization, but that is another nonlinear objective that requires careful weighting, etc.

**Comment by f0uriest** [comment]
Can't we do this by using Two power profile for the existing kinetic profiles?

**Comment by dpanici** [comment]
Possible with share parameters btwn two things

**Comment by dpanici** [comment]
Not planned, could do with above or just penalize pressure, or fix a certain part of the T,n
