### ISSUE TITLE
Geometry branch: Error when using continuation parameters for resolution

### ISSUE THREAD

**Issue by patil3** [PlasmaControl/DESC#113]
Using the geometry branch installation, I tried using continuation parameters (input file: qhs46_test.txt). The code runs into an error when changing the resolution (see error_geomtest.txt). The text output is included in disp.txt.
Output file is attached (qhs46_geomtest.zip).
[qhs46_test.txt](https://github.com/PlasmaControl/DESC/files/6760151/qhs46_test.txt)
[error_geomtest.txt](https://github.com/PlasmaControl/DESC/files/6760148/error_geomtest.txt)
[disp.txt](https://github.com/PlasmaControl/DESC/files/6760156/disp.txt)
[qhs46_geomtest.zip](https://github.com/PlasmaControl/DESC/files/6760152/qhs46_geomtest.zip)

**Comment by ddudt** [comment]
Thanks for raising this issue. It was fixed on the `geometry` branch and is now merged into `master`.

**Comment by patil3** [comment]
The issue seems to persist in the latest master unless I am making an obvious mistake. See disp.txt for the output and error.txt for the error message.
It seems that this happens when continuation is used for pressure_ratio but not when continuation is used for L, M, N. I verified this using the dshape example as well.

To reproduce the issue, 
1. I cloned the code: `git clone https://github.com/ddudt/DESC.git`
2. Installed using `python -m pip install DESC`. This installs `desc-opt-0.4.9+41.g180e759`
3. Then ran `desc -vv qhs46_pres_v2`
[disp.txt](https://github.com/PlasmaControl/DESC/files/6785414/disp.txt)
[error.txt](https://github.com/PlasmaControl/DESC/files/6785415/error.txt)
[qhs46_pres_v2.txt](https://github.com/PlasmaControl/DESC/files/6785416/qhs46_pres_v2.txt)
