### ISSUE TITLE
Field Line Tracing Class

### ISSUE THREAD

**Issue by dpanici** [PlasmaControl/DESC#115]
- Should expand the field line tracer to be its own class, which would take in an equilibrium (or more generally, a magnetic field's cylindrical components on a rho,theta,zeta or R,phi,Z grid to allow for coil-produced magnetic fields) and return trajectories of magnetic field lines

- Also currently is implemented using scipy radial basis functions to allow for interpolation on an irregular R,Z,phi grid, but this is very slow and probably will not play well with JAX if we want to use field line trajectories as part of what we optimize for. Our own implementation of interpolation will likely be necessary

**Comment by dpanici** [comment]
Also should add feature to make poincare plots of field lines passing through a given phi=constant poloidal plane

**Comment by f0uriest** [comment]
differentiable ode integration with JAX: 
https://github.com/google/jax/blob/main/jax/experimental/ode.py

**Comment by f0uriest** [comment]
Also we might be able to replace the interpolation entirely by direct evaluation of the B field from R,Z,L, especially if we can find a stable way to evaluate zernike polynomials with jax (see #117)
