### ISSUE TITLE
DESC Install: Pip subprocess error

### ISSUE THREAD

**Issue by kfinn2002** [PlasmaControl/DESC#1156]
Hello,

I am installing DESC using conda, following installation "on local machine" option 2a on the installation page. I am on a Windows. Making the environment fails, giving me this error:

Pip subprocess error:
ERROR: Could not install packages due to an OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\Users\\craft\\anaconda3\\envs\\desc-env\\*'

failed

CondaEnvException: Pip failed

I have tried clearing cache, updating pip & conda, updating --all, re-cloning the git project, and following option 2b. Nothing has worked yet. Do you have any fixes for this?

Thank you!

**Comment by dpanici** [comment]
Hi! 

So if you are on Windows, you will need to install DESC in the Windows Subsystem for Linux, as JAX does not support Windows well. The instructions for doing so are [here](https://learn.microsoft.com/en-us/windows/wsl/install) (should be mainly just typing in `wsl --install` inside a Powershell terminal with admin privileges, then you will have an application called Ubuntu on your laptop and that launches the linux terminal).
I
f there are any issues with the process I am happy to work through them today.

**Comment by kfinn2002** [comment]
Hello again, 

I successfully downloaded DESC though Ubuntu, however trying to setup the env in conda still gives me this pip subprocess issue:

Pip subprocess error:
ERROR: Could not install packages due to an OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\Users\\craft\\anaconda3\\envs\\desc-env\\*'


failed

CondaEnvException: Pip failed

Thank you

**Comment by dpanici** [comment]
What commands are you running and where?

**Comment by kfinn2002** [comment]
The problem was resolved. I was able to ignore the PIP error and run DESC after my env was setup. I used the conda prompt to do env setup after cloning the DESC github through Ubuntu.

Thank you for your help!
