### ISSUE TITLE
Issue with pip install desc-opt

### ISSUE THREAD

**Issue by mjrich99** [PlasmaControl/DESC#1157]
Ran into the following error using pip install desc-opt

Collecting nvgpu (from desc-opt)
  Using cached nvgpu-0.10.0.tar.gz (8.4 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
Note: you may need to restart the kernel to use updated packages.
  error: subprocess-exited-with-error
  
  python setup.py egg_info did not run successfully.
  exit code: 1

**Comment by f0uriest** [comment]
it looks like it might be an issue with using cached dependencies. Can you try
`pip install --no-cache-dir desc-opt`

**Comment by mjrich99** [comment]
Unfortunately that still had the same error. Here's more of the output

Collecting nvgpu (from desc-opt)
  Downloading nvgpu-0.10.0.tar.gz (8.4 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
Note: you may need to restart the kernel to use updated packages.
  error: subprocess-exited-with-error
  
  python setup.py egg_info did not run successfully.
  exit code: 1
  
  [13 lines of output]
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "C:\Users\mjrich\AppData\Local\Temp\pip-install-rvd_620g\nvgpu_bd159b5317ae4945847539d35275a67f\setup.py", line 33, in <module>
      long_description=read_file('README.md'),
                       ^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\mjrich\AppData\Local\Temp\pip-install-rvd_620g\nvgpu_bd159b5317ae4945847539d35275a67f\setup.py", line 6, in read_file
      return f.read()
             ^^^^^^^^
    File "C:\ProgramData\anaconda3\Lib\encodings\cp1252.py", line 23, in decode
      return codecs.charmap_decode(input,self.errors,decoding_table)[0]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 4846: character maps to <undefined>
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

**Comment by dpanici** [comment]
Ah, are you on Windows? You should look at my answer in #1156 , on Windows you need to first install the Windows Subsystem for Linux, then install DESC through the linux terminal

**Comment by R2-Ski2** [comment]
I am having the same problem. I have installed Windows Subsystem for Linux but it is telling me I cannot use pip.

mcassens@DESKTOP-O2C6T2L:~$ pip install desc-opt
Command 'pip' not found, but can be installed with:
sudo apt install python3-pip
mcassens@DESKTOP-O2C6T2L:~$ sudo apt install python3-pip desc-opt
[sudo] password for mcassens:
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package python3-pip is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python3-pip' has no installation candidate
E: Unable to locate package desc-opt

Is there a different way I should be installing?

**Comment by dpanici** [comment]
Try `sudo apt-get update` then `sudo apt install python3-pip` and see if that installs pip

`desc-opt` is a `pip` packages so it must be installed through pip like `pip install desc-opt` once `pip` is installed

**Comment by R2-Ski2** [comment]
This is what came up:

Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement juypterlab (from versions: none)
ERROR: No matching distribution found for juypterlab

**Comment by dpanici** [comment]
This is on the Linux terminal?

**Comment by R2-Ski2** [comment]
Yes

**Comment by dpanici** [comment]
Maybe try `python3 -m pip install jupyterlab`

**Comment by R2-Ski2** [comment]
Okay that worked but now I am getting No web browser found: Error('could not locate runnable browser')

**Comment by dpanici** [comment]
I think https://github.com/jupyter/notebook/issues/4594#issuecomment-565805648 has the solution

> I have found how to fix this - i..e to have jupyter notebook launch from WSL in a windows web browser. There is a setting in the jupyter_notebook_config.py to force notebook to launch using the URL, not a redirect file.
    
>c.NotebookApp.use_redirect_file = False
  (default is True)
  
>If you have your browser environment variable set, then running 'jupyter notebook' should now open it with  
  http://localhost:8888/tree instead of the redirect file by default.

**Comment by dpanici** [comment]
This might also work if the above does not: https://github.com/jupyter/notebook/issues/4594#issuecomment-562359841

**Comment by dpanici** [comment]
Closing as resolved
