### ISSUE TITLE
Quadratic flux minimizing surfaces 

### ISSUE THREAD

**Issue by f0uriest** [PlasmaControl/DESC#1162]
A few people also asked if this was possible. I think it could be but we'd need to modify the QuadraticFlux objective to allow the surface to vary? Or make a new objective for it?

**Comment by dpanici** [comment]
I would be fine with modifying the quadratic flux objective, originally it could let both change anyways

**Comment by dpanici** [comment]
- add warning if eq is passed and allowed to change, to use VacuumBoundaryError instead
