### ISSUE TITLE
zeta_B computation is sometimes wrong

### ISSUE THREAD

**Issue by unalmis** [PlasmaControl/DESC#1163]
Sometimes when I rerun the test that compares everything is computed the same as master up to floating point errors, I get significant errors on `zeta_B`.

```sh
Not equal to tolerance rtol=1e-10, atol=1e-10
Parameterization: desc.magnetic_fields._core.OmnigenousField. Name: zeta_B.
Mismatched elements: 270 / 297 (90.9%)
Max absolute difference: 11.42397329
Max relative difference: 34.0466585
 x: array([ 0.      ,  0.550532,  1.076765,  1.557329,  1.976363,  2.325429,
        2.604526,  2.822094,  2.993993,  0.      ,  0.550532,  1.076765,
        1.557329,  1.976363,  2.325429,  2.604526,  2.822094,  2.993993,...
 y: array([0.      , 0.550532, 1.076765, 1.557329, 1.976363, 2.325429,
       2.604526, 2.822094, 2.993993, 0.      , 0.550532, 1.076765,
       1.557329, 1.976363, 2.325429, 2.604526, 2.822094, 2.993993,...
```

This error is not always reproducible. However,  it has even occurred on new branches, even when the file that the results are compared to  was regenerated immediately prior to running the test.

Therefore, either

1. `zeta_B` is not deterministic or subject to a numerical instability (silly)
2. Pickle is messing something up when the file is dumped
3. Some issue from changes to this test in #1027 ?

**Comment by f0uriest** [comment]
Could they be the same modulo 2pi/NFP?

**Comment by YigitElma** [comment]
Is this `test_compute_everthing`? #1027 only added `xyz` computation to the test, it didn't change logic or etc.

**Comment by unalmis** [comment]
> Could they be the same modulo 2pi/NFP?

I checked: no. This is reproducible on my machine. Repeated calls to the test give 40/60 pass,fail split respectively, sample size 8. It is consistent in that when the failure occurs it is always the same result. I'm now leaning towards option 1.

> Is this `test_compute_everthing`? #1027 only added `xyz` computation to the test, it didn't change logic or etc.

Yes it looked fine when we merged. I think it was around time failure starts occurring.


```python
@register_compute_fun(
    name="zeta_B",
    label="\\zeta_{B}",
    units="rad",
    units_long="radians",
    description="Boozer toroidal angular coordinate",
    dim=1,
    params=[],
    transforms={},
    profiles=[],
    coordinates="rtz",
    data=["zeta", "nu"],
    # default parameterization is equilibrium
)
def _zeta_B(params, transforms, profiles, data, **kwargs):
    data["zeta_B"] = data["zeta"] + data["nu"]
    return data

....
# in data_index.py
_class_inheritance = {
    ...
    "desc.magnetic_fields._core.OmnigenousField": [], # Shouldn't this include equilibrium?
}
```
