### ISSUE TITLE
Change equations to match physics

### ISSUE THREAD

**Issue by unalmis** [PlasmaControl/DESC#1176]
I would prefer to keep stuff like this as independent quantities. For stuff like `g_rt` and `g_tr`, those are the same both physically and numerically, independent of how we parameterize or discretize things.

Stuff like `theta_PEST_tt` and `lambda_tt` are actually different things physically, its just that they happen to the same numerically because we define `theta_PEST = theta + lambda`, but in theory other relations are possible and equally valid physically.

_Originally posted by @f0uriest in https://github.com/PlasmaControl/DESC/pull/1175#discussion_r1713107215_

**Comment by unalmis** [comment]
In that case I have created the linked branch to reflect that. @f0uriest  you confirm with a thumbs up / thumbs down whether you still want to create new compute functions that just do `data["theta_PEST_z"] = data["lambda_z"]; return data` ? This could be a couple thousand lines of code. Maybe also @ddudt since related to #1171.

**Comment by f0uriest** [comment]
Ideally yes, I'd like to keep them separate, but we don't have to do everything at once. The main point was to not remove existing things and replace them with aliases (and as we add new things try to keep to that convention).
