### ISSUE TITLE
Boozer bug

### ISSUE THREAD

**Issue by unalmis** [PlasmaControl/DESC#1178]
When we construct the Fourier harmonics of B in the boozer representation, we interpolate from the covariant components of the DESC coordinate system, when we should instead interpolate on the PEST straight field line coordinate system.

**Comment by unalmis** [comment]
There's nothing that in theory prevents doing the former, but the math we use assumes the latter

**Comment by f0uriest** [comment]
Are you sure? I thought ours was based on the VMEC->boozer coordinate transformation which would also be using theta_DESC not theta_PEST

**Comment by unalmis** [comment]
Let me check again to make sure I didn't get confused
