### ISSUE TITLE
RecursionError when attempting to plot coilset within DESC

### ISSUE THREAD

**Issue by jmathewson1869** [PlasmaControl/DESC#1195]
After loading a makegrid coilset from a VMEC input I am able to solve for an equilibrium(that is incorrect), however when I attempt to plot the coilset, it gives me the error shown. Any help would be much appreciated. 

[DESC_GABRIEL_ROT_ELLIPSE.md](https://github.com/user-attachments/files/16630018/DESC_GABRIEL_ROT_ELLIPSE.md)

**Comment by f0uriest** [comment]
```python
coil_sym = r"coils.rotatingellipse"

field = MixedCoilSet.from_makegrid_coilfile(coil_sym,method='linear')

plot_coils(coil_sym)
```

it looks like you're trying to plot the string `coil_sym` not the actual loaded coilset `field` (though we could probably make a better error message)

**Comment by jmathewson1869** [comment]
Sorry to just be seeing this. Have been busy with my other job. But yes
this works! Thank you for the help.
