### ISSUE TITLE
Rotating ellipse test equilibrium not rotating

### ISSUE THREAD

**Issue by jmathewson1869** [PlasmaControl/DESC#1217]
I am able to solve for an equilibrium from an mgrid coil file. However, when plotting the surfaces, they do not seem to vary as phi changes. Any help would be much appreciated. 
[MGRID_COILS.zip](https://github.com/user-attachments/files/16700744/MGRID_COILS.zip)

**Comment by f0uriest** [comment]
It looks like you're just calling `eq.solve` on the initial guess, which will solve a fixed boundary problem with the initial surface shape you give. After that you'll need to use the `{Vacuum}BoundaryError` objectives and `eq.optimize` to actually change the boundary shape to match the external field, see https://desc-docs.readthedocs.io/en/stable/notebooks/tutorials/free_boundary_equilibrium.html

**Comment by f0uriest** [comment]
Also note that the initial guess for a free boundary run generally needs to have roughly the correct major and minor radius, and fit inside any external coils, so you may need to modify the initial guess depending on the shape of your external field.

**Comment by jmathewson1869** [comment]
Ok thank you for the help, I’ll check and see, I think the input has the
bounds that I set. But I’ll make sure.

Best,
James

**Comment by dpanici** [comment]
Closing as assumed resolved, feel free to reopen if there are still issues @jmathewson1869
