### ISSUE TITLE
`maybe_add_self_consistency` doesn't work for single-stage optimization

### ISSUE THREAD

**Issue by ddudt** [PlasmaControl/DESC#1234]
The optimizer only calls `maybe_add_self_consistency` if the objective is **not** a `ProximalProjection`. This means it will not get called in single-stage optimization, and the corresponding curve constraints will not be applied. 

A possible solution would be to split `maybe_add_self_consistency` into two separate functions: one for constraints applied to the `Equilibrium` and another for all other things. The former would still only be applied when the objective is not a `ProximalProjection`, but the latter would always get called for all optimizations. This is because the proximal optimizer has special logic specific to equilibria. 

Obviously the user can manually add them for now to make this work.

**Comment by dpanici** [comment]
#1236 should take this into account
