### ISSUE TITLE
Changing the solver of an equilibrium will not change the underlying optimizer method

### ISSUE THREAD

**Issue by dpanici** [PlasmaControl/DESC#124]
Per title,  it is possible to load in an equilibrium (say in a jupyter notebook), change its solver (`eq.solver='scipy-bfgs'` for example), then when you go to solve it does not use the new solver, because it actually uses the existing optimizer's `eq.optimizer.method` as the solving method. 

I think we just need to add something to the setter method of eq.solver that will re-init the optimizer if the solving method changes.

**Comment by f0uriest** [comment]
i don't think there is an attribute `eq.solver`, do you mean `eq.optimizer`?

**Comment by f0uriest** [comment]
Also note that this will all change a fair amount with the new objective function stuff

**Comment by dpanici** [comment]
Ah you are right, there is no `eq.solver`,  I was mistaken. My bad, let me close this then.
