### ISSUE TITLE
Issue with Package Installation - UnicodeDecodeError

### ISSUE THREAD

**Issue by KevPlatas** [PlasmaControl/DESC#1253]
Dear DESC Development Team,

I am encountering a recurring issue while trying to install the DESC package. The installation process fails with the following error:

error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\gears\AppData\Local\Temp\pip-install-mecpsmz1\nvgpu_ed47ce7e68004203ba2b60532913bcf3\setup.py", line 33, in <module>
          long_description=read_file('README.md'),
                           ^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\gears\AppData\Local\Temp\pip-install-mecpsmz1\nvgpu_ed47ce7e68004203ba2b60532913bcf3\setup.py", line 6, in read_file
          return f.read()
                 ^^^^^^^^
        File "C:\Users\gears\anaconda3\envs\desc_env\Lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 4846: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

It appears that the error is related to a UnicodeDecodeError due to encoding issues in the setup.py file, specifically while reading the README.md file. I have tried various solutions, including ensuring the file encoding is set to UTF-8, but the problem persists.

Could you please provide guidance or an update on this issue? Any assistance in resolving this would be greatly appreciated.

Thank you for your help.

Best regards,
Kevin Platas

**Comment by rahulgaur104** [comment]
Hi Kevin,

Are you trying to install with pip (Option 1)? Have you tried [Option 2 explained here](https://desc-docs.readthedocs.io/en/latest/installation.html)? Can you give us the exact steps you followed and tell us a bit more about your hardware(laptop/cluster) and OS?

Best,
Rahul

**Comment by dpanici** [comment]
I see that you are using Windows, we do not test our code nor endorse that it can be installed on Windows (I've been told it is possible but very painful and I have not done so myself)

I would highly suggest using the Windows Subsystem for Linux and installing the code on that. See #1156 and #1157   for more detail, and let me know if this does not work, or if you have further questions

**Comment by dpanici** [comment]
Closing because this is a Windows issue, not a DESC issue, feel free to re-open if you still have issues or further questions
