### ISSUE TITLE
`most_rational` goes into an infinite loop when given two negative arguments

### ISSUE THREAD

**Issue by cfe316** [PlasmaControl/DESC#1265]
On the `master` branch, `most_rational` (defined in `grid.py`) fails for two negative numbers by going into an infinite loop.

I think this must not be very important or it would have been fixed earlier, but the function seems to contain some facilities for dealing with negative arguments, but it fails when I actually try it. For example

`most_rational(-2, -1)` and `most_rational(-1, -2)` both fail.
I think this could be fixed by switching the order of the two blocks of code that flip a negative range to a positive range, and the one that switches `a` and `b` if `a > b`.

Happy to try to fix this is a "good first issue".

**Comment by dpanici** [comment]
I've not looked at this closely, but if you have a fix feel free to contribute a PR!

**Comment by lisamessier** [comment]
https://github.com/PlasmaControl/DESC/pull/1269
