### ISSUE TITLE
Question about Quasiymetry two term objective

### ISSUE THREAD

**Issue by mohawk811** [PlasmaControl/DESC#1281]
Hello,

I had a question about a warning I am getting about the poloidial resolution for my RotationalTransform objective:

"RotationalTransform objective grid requires poloidal resolution for surface averages"

```

    grid2 = LinearGrid(
         M=eq.M, N=eq.N, NFP=eq.NFP, rho=np.array([1.0]), sym=True
    )
```
This is how I am prescribing my grid, as I just want to optimize the boundary. I have my poloidal resolution prescribed, is the resolution not high enough or is this just a consequence of optimizing the boundary.

**Comment by rahulgaur104** [comment]
Hi @mohawk811 ,
Can you provide a minimal working example that throws the warning?

**Comment by mohawk811** [comment]
I resolved the issue, I was prescribing a radial resolution and feeding that into my RotationalTransform Objective, which conflicted with rho =1.0
` grid2 = LinearGrid(
         M=eq.M, N=eq.N, NFP=eq.NFP, rho=np.array([1.0]), sym=True
    )`
`RotationalTransform(eq=eq, grid=grid2, bounds=(.15,.35))`
