### ISSUE TITLE
VMEC inputs

### ISSUE THREAD

**Issue by Alan-Goodman** [PlasmaControl/DESC#1298]
Clearer instructions to load a vmec input file (not from the command line, and without specifying e.g. profiles in code) would be useful:)

**Comment by f0uriest** [comment]
We could probably add a `from_input_file` method to `Equilibrium` and `EquilibriaFamily` to streamline this

On a related note, a few people have asked me about an "easy" way to use VMEC input files that use splines for profiles. I think this might be possible?

**Comment by dpanici** [comment]
`from_input_file` as a method of `Equilibrium`

**Comment by dpanici** [comment]
> We could probably add a `from_input_file` method to `Equilibrium` and `EquilibriaFamily` to streamline this
> 
> On a related note, a few people have asked me about an "easy" way to use VMEC input files that use splines for profiles. I think this might be possible?

Kicking this particular can down the line #183
