### ISSUE TITLE
Computing Quasi Symmetry two term issues

### ISSUE THREAD

**Issue by mohawk811** [PlasmaControl/DESC#1308]
Hello!
I am having some inconsistencies with computing the Quasi Symmetry two term values when comparing two equilibria. One has very good symmetry the other does not. This does not appear to be reflected when I plot the geodesic curvature for an equilibria with a QS error color scale my code is :

```python
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.collections import LineCollection

eq_out = desc.io.load(r'eq_opt_qs_4_aspect_6__elongation2_09_15.h5')
eq_out2 = desc.io.load(r'eq_opt_geodesic_3_aspect6_10_16.h5')

grid = LinearGrid(M=eq_out.M_grid, N=eq_out.N_grid, NFP=eq_out.NFP, rho=np.array([1.0]), sym=True)

kappa_g_qs=eq_out.compute('kappa_g',grid=grid)['kappa_g']
kappa_g_g=eq_out2.compute('kappa_g',grid=grid)['kappa_g']

# Compute kappa_g and f_C for both QS target and Geodesic
kappa_g_qs = eq_out.compute('kappa_g', grid=grid)['kappa_g']  # Y-axis for QS target
kappa_g_g = eq_out2.compute('kappa_g', grid=grid)['kappa_g']  # Y-axis for Geodesic

f_C_qs = eq_out.compute('f_C', grid=grid)['f_C']  # Color scale for QS target
f_C_g = eq_out2.compute('f_C', grid=grid)['f_C']  # Color scale for Geodesic

# Assuming x represents boundary values (this should correspond to your data)
x = np.linspace(0, 1, len(kappa_g_qs))  # X-axis values (e.g., boundary points)

# Find min/max across both f_C arrays for the colorbar range
f_C_min = min(f_C_qs.min(), f_C_g.min())
f_C_max = max(f_C_qs.max(), f_C_g.max())

# Create segments for the QS target line
points_qs = np.array([x, kappa_g_qs]).T.reshape(-1, 1, 2)
segments_qs = np.concatenate([points_qs[:-1], points_qs[1:]], axis=1)

# Create a LineCollection for the QS target with f_C as the color scale
lc_qs = LineCollection(segments_qs, cmap='viridis')
lc_qs.set_array(f_C_qs)  # Set the f_C values for the QS target color
lc_qs.set_clim(f_C_min, f_C_max)  # Set the color range to be shared

# Create segments for the Geodesic line
points_g = np.array([x, kappa_g_g]).T.reshape(-1, 1, 2)
segments_g = np.concatenate([points_g[:-1], points_g[1:]], axis=1)

# Create a LineCollection for the Geodesic with the same color scale
lc_g = LineCollection(segments_g, cmap='viridis')
lc_g.set_array(f_C_g)  # Set the f_C values for the Geodesic color
lc_g.set_clim(f_C_min, f_C_max)  # Set the same color range for consistency

# Create the plot
fig, ax = plt.subplots()

# Add both LineCollections to the plot
ax.add_collection(lc_qs)
ax.add_collection(lc_g)


# Set plot limits
ax.set_xlim(x.min(), x.max())
ax.set_ylim(min(kappa_g_qs.min(), kappa_g_g.min()), max(kappa_g_qs.max(), kappa_g_g.max()))

# Add a single shared colorbar for f_C
cbar = plt.colorbar(lc_qs, ax=ax)  # Use lc_qs or lc_g, both have the same color limits
cbar.set_label('f_C (Shared Color Scale)')

# Add axis labels
plt.ylabel('Geodesic Curvature (kappa_g)')
plt.xlabel('Values at the boundary')

# Display the plot
plt.show()
```
The associated plots are shown below:
 
<img width="420" alt="Screenshot 2024-10-17 at 11 19 08 AM" src="https://github.com/user-attachments/assets/20a4f27b-2923-4125-bbf9-65338d534124">
<img width="417" alt="Screenshot 20

<img width="421" alt="Screenshot 2024-10-17 at 11 19 33 AM" src="https://github.com/user-attachments/assets/d6e7268a-b7c4-40f9-97f3-cbd718fddf4b">
24-10-17 at 11 19 15 AM" src="https://github.com/user-attachments/assets/923cdc68-be9f-4752-bfa0-9d5444845ec4">

<img width="417" alt="Screenshot 2024-10-17 at 11 19 15 AM" src="https://github.com/user-attachments/assets/b1ba4eb0-b5aa-4589-b004-e2f7cf5196e3">

**Comment by mohawk811** [comment]
Some follow up clarification and context, I am interested in Quasi Polodial Configurations. And each line in my home made plot is the array values of the corresponding equilibria

**Comment by rahulgaur104** [comment]
```
I am having some inconsistencies with computing the Quasi Symmetry two term values when comparing two equilibria. One has very good symmetry the other does not. This does not appear to be reflected when I plot the geodesic curvature for an equilibria with a QS error color scale my code is
```

Can you explain this a little better? You have two equilibria: one QP and one far from QP and you want to compare their geodesic curvatures? Do you expect the curvature to behave a certain way?

```
This does not appear to be reflected when I plot the geodesic curvature for an equilibria with a QS error color scale my code is
```
What does this sentence mean?

**Comment by mohawk811** [comment]
So in theory zero geodesic curvature should imply good qp symmetry. But my optimization results say otherwise. For this plot I just want to see how the geodesic curvature target and the qs two term targets compare when we have two equilibria with similar aspect ratio/elongation.

I just want to be able to see if there is some sort of scaling for good qp symetry and geodesic curvature. So I have plotted the geodesic curvature targets for two equilibria. What I hope to see with this plot is that there is some correlation with geodesic curvature and QP error. The issue is when I do eq.compute 'f_C' for the equilibria with the bad Mod B plot it says it has good symmetry which doesnt match with what I am seeing in the mod B plot

**Comment by mohawk811** [comment]
I feel the issue is something that I am doing wrong when I compute 'f_C' but yeah I'm not sure what im doing wrong

**Comment by rahulgaur104** [comment]
Two term quasisymmetry requires a helicity, which for your case should be (0, eq.NFP). I think you need to provide that to the compute function.

```
f_C = eq_out.compute('f_C', grid=grid, helicity=(0, eq.NFP))['f_C']
```

**Comment by mohawk811** [comment]
I've made this addition but I still get the same issue. Some clarifying points, in my optimization I am only optimizing the boundary and only care about the f_C on the last surface.

**Comment by mohawk811** [comment]
<img width="419" alt="Screenshot 2024-10-17 at 2 10 24 PM" src="https://github.com/user-attachments/assets/a1f07767-2ba6-4048-ad62-2eaf6dc7b4c5">
<img width="429" alt="Screenshot 2024-10-17 at 2 10 35 PM" src="https://github.com/user-attachments/assets/15da6e50-535c-446c-9e4d-62494fbf9582">

**Comment by mohawk811** [comment]
If I print out both arrays I get f_C values very close to zero, but that should not be the case(mod B plot above)

**Comment by ddudt** [comment]
Can you please re-post your custom plot with the correct `f_C` values from using the proper QP helicity? 

Can you also check that your equilibria are well-converged to solutions with low force balance errors?

**Comment by dpanici** [comment]
And what does the boundary look like for the one with the poor QP boozer surface plot?

**Comment by mohawk811** [comment]
`import numpy as np
import matplotlib.pyplot as plt
from matplotlib.collections import LineCollection

eq_out = desc.io.load(r'Directory_to_plot_overall_qp_trends/eq_opt_qs_4_aspect_6__elongation2_09_15.h5')
eq_out2 = desc.io.load(r'eq_opt_geodesic_3_aspect6_10_16.h5')

grid = LinearGrid(M=eq_out.M_grid, N=eq_out.N_grid, NFP=eq_out.NFP, rho=np.array([1.0]), sym=True)

kappa_g_qs=eq_out.compute('kappa_g',grid=grid)['kappa_g']
kappa_g_g=eq_out2.compute('kappa_g',grid=grid)['kappa_g']

# Compute kappa_g and f_C for both QS target and Geodesic
kappa_g_qs = eq_out.compute('kappa_g', grid=grid)['kappa_g']  # Y-axis for QS target
kappa_g_g = eq_out2.compute('kappa_g', grid=grid)['kappa_g']  # Y-axis for Geodesic

f_C_qs = eq_out.compute('f_C', grid=grid, helicity=(0,eq_out.NFP))['f_C']  # Color scale for QS target
f_C_g = eq_out2.compute('f_C', grid=grid, helicity=(0,eq_out2.NFP))['f_C']  # Color scale for Geodesic

# Assuming x represents boundary values (this should correspond to your data)
x = np.linspace(0, 1, len(kappa_g_qs))  # X-axis values (e.g., boundary points)

# Find min/max across both f_C arrays for the colorbar range
f_C_min = min(f_C_qs.min(), f_C_g.min())
f_C_max = max(f_C_qs.max(), f_C_g.max())

# Create segments for the QS target line
points_qs = np.array([x, kappa_g_qs]).T.reshape(-1, 1, 2)
segments_qs = np.concatenate([points_qs[:-1], points_qs[1:]], axis=1)

# Create a LineCollection for the QS target with f_C as the color scale
lc_qs = LineCollection(segments_qs, cmap='viridis')
lc_qs.set_array(f_C_qs)  # Set the f_C values for the QS target color
lc_qs.set_clim(f_C_min, f_C_max)  # Set the color range to be shared

# Create segments for the Geodesic line
points_g = np.array([x, kappa_g_g]).T.reshape(-1, 1, 2)
segments_g = np.concatenate([points_g[:-1], points_g[1:]], axis=1)

# Create a LineCollection for the Geodesic with the same color scale
lc_g = LineCollection(segments_g, cmap='viridis')
lc_g.set_array(f_C_g)  # Set the f_C values for the Geodesic color
lc_g.set_clim(f_C_min, f_C_max)  # Set the same color range for consistency

# Create the plot
fig, ax = plt.subplots()

# Add both LineCollections to the plot
ax.add_collection(lc_qs)
ax.add_collection(lc_g)


# Set plot limits
ax.set_xlim(x.min(), x.max())
ax.set_ylim(min(kappa_g_qs.min(), kappa_g_g.min()), max(kappa_g_qs.max(), kappa_g_g.max()))

# Add a single shared colorbar for f_C
cbar = plt.colorbar(lc_qs, ax=ax)  # Use lc_qs or lc_g, both have the same color limits
cbar.set_label('f_C (Shared Color Scale)')

# Add axis labels
plt.ylabel('Geodesic Curvature (kappa_g)')
plt.xlabel('Values at the boundary')

# Display the plot
plt.show()`

**Comment by mohawk811** [comment]
So I did 2D plots of the boundary and there seems to be inconsistencies. So for the equilibria where I target zero geodesic curvature, below are plots of kappa_g 
<img width="680" alt="Screenshot 2024-10-17 at 8 37 53 PM" src="https://github.com/user-attachments/assets/9e3227fe-3fbe-4e80-b635-808705afe4e7">
and f_C
<img width="399" alt="Screenshot 2024-10-17 at 8 28 39 PM" src="https://github.com/user-attachments/assets/0c01d37b-ff38-45f8-85b6-471c4e4162de">
<img width="423" alt="Screenshot 2024-10-17 at 8 28 46 PM" src="https://github.com/user-attachments/assets/8d39910f-5026-47c9-96bb-d0309546fcbc">

**Comment by mohawk811** [comment]
looking at the optimization messages it seems like I have force errors:

`Maximum absolute Force error:                                8.048e+04  -->   2.105e+03 (N)
Minimum absolute Force error:                                8.806e-02  -->   4.085e-03 (N)
Average absolute Force error:                                3.322e+02  -->   1.168e+02 (N)`

**Comment by rahulgaur104** [comment]
'
So I did 2D plots of the boundary and there seems to be inconsistencies. So for the equilibria where I target zero geodesic curvature, below are plots of kappa_g
'
What inconsistencies are you referring to? Weak correlation b/w kappa_g and QS error?

Absolute force errors are not very helpful. Can you post normalized force errors?

**Comment by mohawk811** [comment]
Maximum absolute Force error:                                1.175e+01  -->   3.074e-01 (normalized)
Minimum absolute Force error:                                1.286e-05  -->   5.965e-07 (normalized)
Average absolute Force error:                                4.852e-02  -->   1.705e-02 (normalized)

So if we have zero kappa_g with no current it should give us a qp equilibria. The Mod B plots dont have that symmetry. The inconsistency that I'm getting is that the 2d plot of 'f_C' on the boundary is much lower than what is plotted on the plot_qs_error plot

**Comment by rahulgaur104** [comment]
Yeah, force balance is not great! 
An acceptable equilibrium must have max. normalized force balance error < 1E-3.

Please make sure that you have good ideal MHD force balance. If you are not in equilibrium, things like QS etc. don't make a lot of sense because the fields you are using probably won't exist.

**Comment by mohawk811** [comment]
This makes a lot more sense in my head. I will go back and check this over and reach out again if I have any issues.

**Comment by mohawk811** [comment]
Is there a varible I could plot to get the normalized force error for equilibria I already have to just verify?

**Comment by rahulgaur104** [comment]
The best way is to use 

`
fig, ax = plot_section(eq, name="|F|", norm_F=True, log=True)
`
or if you want the plot without log
`
fig, ax = plot_section(eq, name="|F|", norm_F=True, log=False)
`

Here's what these plots should look like for a  MHD stable finite beta equilibrium close to OP

![OP_normF_plot](https://github.com/user-attachments/assets/5129ef54-c245-4887-ab27-fc75b4c3aaff)
![OP_normF_plot_nolog](https://github.com/user-attachments/assets/35f11eb0-1cea-4e43-a1ba-30f80beb4f80)
[Boozer_contour_plot_OP_rho1.0_optimized.pdf](https://github.com/user-attachments/files/17426689/Boozer_contour_plot_OP_rho1.0_optimized.pdf)

**Comment by rahulgaur104** [comment]
@mohawk811 does this resolve your issue?

**Comment by mohawk811** [comment]
Yes this makes a lot more sense. I plan on redoing the optimization but instead of optimizing the boundary the volume

**Comment by rahulgaur104** [comment]
Or you can also add ForceBalance to the objectives and constraints. 
Anywho, I think we have figured out what the problem was and now can declare this issue resolved.
