### ISSUE TITLE
Current to iota conversion near the magnetic axis

### ISSUE THREAD

**Issue by rahulgaur104** [PlasmaControl/DESC#1310]
The iota value is correct when we use L'hopital rule on axis but the iota profile changes sharply for equilibria with very large current, typically a tokamak equilibria (10s of Mega Amps).

We can either
- Keep higher-order terms using Taylor series(essentially L'Hopital like expansion) to get the near-axis behaviour
- Converting the current to iota globally instead of pointwise

**Comment by f0uriest** [comment]
Can you explain a bit what you mean? Do you have an example?

**Comment by rahulgaur104** [comment]
Have you seen Dario's attempt at reconstructing the iota profile for a DIII-D equilibrium? I'll ask him to share his reconstructed iota profile.

**Comment by dpanici** [comment]
Closing as I think this is more an issue with profile fitting than with the iota computation
