### ISSUE TITLE
Full grid is overriden to symmetric grid

### ISSUE THREAD

**Issue by unalmis** [PlasmaControl/DESC#1313]
When I make a compute function with
```python
resolution_requirement="tz",
grid_requirement={"coordinates": "rtz", "is_meshgrid": True, "sym": False}
```
and use `eq.compute` for that function, the full grid I supply is overridden to a symmetric one. The compute function catches this error, complaining that a full grid is required.

In general, I should not need to specify `override_grid=False` here because I am fine with the grid being overriden when computing dependencies.

**Comment by unalmis** [comment]
#1094 is a good branch to resolve this because it has quantities that require non-symmetric grids

**Comment by dpanici** [comment]
Here, the behavior we want to change would just be for the grid override to catch when `sym=False` is a requirement and use that for the computational grid, right?

**Comment by unalmis** [comment]
Yes, setting grid.sym on the overriding grids based on grid requirement will solve it
