### ISSUE TITLE
Ways to save optimization output messages? (saving verbose=3 messages)

### ISSUE THREAD

**Issue by mohawk811** [PlasmaControl/DESC#1314]
Hi, I was wondering if there was a way to save the optimization output messages and perhaps the associated file?

Currently this is the way I run the optimizer:

`
    eq_new, history = eq.optimize(
        objective=objective,
        constraints=constraints,
        optimizer=optimizer,
        maxiter=1000,  # we don't need to solve to optimality at each multigrid step
        verbose=3,
        copy=True,  # don't modify original, return a new optimized copy
        options={
            # Sometimes the default initial trust radius is too big, allowing the
            # optimizer to take too large a step in a bad direction. If this happens,
            # we can manually specify a smaller starting radius. Each optimizer has a
            # number of different options that can be used to tune the performance.
            # See the documentation for more info.
            "initial_trust_ratio": 1.0,
        },
    )
    return eq_new
`
    
    
    
    The associated scan in my calculation:
    
    `for a in range(10,12):
    for i in range(5):
        if i==0:
            #eq = desc.io.load("eq_opt_geodesic_22.h5")
            #eq.solve()
            Psi = 0.023050438527737336
            surf = FourierRZToroidalSurface.from_qp_model(
            major_radius=1,
            aspect_ratio=a, #scan over
            elongation=2,
            mirror_ratio=0.1, #Scan over add objective target
            torsion=0, #independent
            NFP=2, #Scan over
            sym=True,
            positive_iota=True)
            eq = Equilibrium(L=i+2, M=i+2, N=i+2, Psi=Psi, surface=surf)
            eq.solve()
        else:
            eq.change_resolution(L=i+2, M=i+2, N=i+4)
    
            # also change the grid resolutions so the default grids are sufficient for the higher resolutions
            eq.change_resolution(L_grid=2*eq.L, M_grid=2*eq.M, N_grid=2*eq.N)
            eq_new = run_qp_step(k=i,a=a, eq=eq)
            eq_new.save(f"eq_opt_qs_{i}_aspect_{a}_10_18.h5")
            eq=eq_new`

**Comment by ddudt** [comment]
If you are running in an HPC environment, you can save the output to a log file using these command in your slurm script when you submit the job: 
```
#SBATCH --output=log.out
#SBATCH --error=log.err
```

Otherwise you can just pipe the terminal output to a text file: `python script.py |& tee output.txt`
