### ISSUE TITLE
Question about resizing an equilibrium

### ISSUE THREAD

**Issue by mohawk811** [PlasmaControl/DESC#1316]
Hello, I was wondering if I could get help on resizing the precise QA equilibria on desc to fit inside a toroidal vacuum vessel (or at least as close as I can fit it) This is the way I have it set up: 

`eq = get("precise_QA")
grid = LinearGrid(L=eq.L_grid, M=eq.M_grid, N=eq.N_grid, NFP=eq.NFP, rho=np.array([1.0]), sym=True)
# Define the major and minor radius
HBT_R0 = 1.0  # Major radius
HBT_a = 0.25  # Minor radius

# Define the Fourier coefficients for R (radial) and Z (vertical)
# In the old code, R_mn = [HBT_R0, HBT_a] corresponds to n=0, m=0 and n=0, m=1 modes
R_lmn = np.array([HBT_R0, HBT_a])  # Coefficients for R (radial direction, cosine modes)
Z_lmn = np.array([0.0, HBT_a])     # Coefficients for Z (vertical direction, sine mode for m=1)

# Define the mode numbers [m, n] for the Fourier terms
# Use positive for cosine modes and negative for sine modes
# R uses cosine modes: m=0, n=0 (constant) and m=1, n=0 (cosine term)
# Z uses sine modes: m=-1, n=0 for the sine term
modes_R = np.array([[0, 0], [1, 0]])  # Mode numbers for R (cosine modes)
modes_Z = np.array([[0, 0], [-1, 0]])  # Mode numbers for Z (sine mode for m=1)

# Number of field periods (NFP) and symmetry setting
NFP = 1   # Number of field periods (axisymmetric, so NFP=1)
sym = True  # Enforce stellarator symmetry

# Create the new surface using FourierRZToroidalSurface
surf = FourierRZToroidalSurface(
    R_lmn=R_lmn,       # Radial Fourier coefficients
    Z_lmn=Z_lmn,       # Vertical Fourier coefficients
    modes_R=modes_R,   # Mode numbers for R (cosine modes)
    modes_Z=modes_Z,   # Mode numbers for Z (sine modes for Z)
    NFP=NFP,           # Number of field periods
    sym=sym,           # Stellarator symmetry
    check_orientation=False  # Skip orientation check
)

eq = get("precise_QA")
# eq = desc.io.load("input.nfp2ginsburg.h5")
# Psi = 0.023050438527737336
# eq = Equilibrium(L=2, M=2, N=2, Psi=Psi)
# eq=desc.compat.rescale(eq=eq, L=('R0',1))

#eq=desc.compat.rescale(eq=eq, L=('R0',1))
#V = eq.compute('V',grid=grid)['V']

# eq = desc.io.load("input.nfp2ginsburg.h5")
# Psi = 0.023050438527737336
# eq = Equilibrium(L=2, M=2, N=2, Psi=Psi)
#eq.solve()
# eq=desc.compat.rescale(eq=eq, L=('V',.2))
# eq.solve()
#eq = desc.examples.get("precise_QA")
#V = eq.compute('V',grid=grid)['V']
eq=desc.compat.rescale(eq=eq, L=('R0',.5))
eq=desc.compat.rescale(eq=eq, L=('a',.15))
fig, ax = plt.subplots(figsize=(8, 8))  # Create a figure and axis

# Plot the boundary of 'surf' on the same axis
plot_boundary(surf, ax=ax,phi=8)  # Pass the 'ax' to plot on the same figure

# Plot the boundary of 'eq_out' on the same axis
plot_boundary(eq, ax=ax,phi=8)  # Pass the same 'ax'

# Display the combined plot
plt.show()`

It seems like the way I have it set up I can only manipulate just one variable at a time. Does anyone have any advice on how to resize this equilibria so that I could have the best intial condition?

**Comment by mohawk811** [comment]
<img width="570" alt="Screenshot 2024-10-22 at 10 31 27 AM" src="https://github.com/user-attachments/assets/daa69307-f9b6-45a4-a6c8-5114339fa926">

**Comment by ddudt** [comment]
You can just use [desc.compat.rescale](https://github.com/PlasmaControl/DESC/blob/master/desc/compat.py#L154). You can specify either the new major or minor radius, but not both (or the volume). In your case you probably want to choose the minor radius such that it will fit in your toroidal vacuum vessel, and keep in mind that it is an "average" minor radius across all the toroidal cross-sections. 

You don't need to re-solve the equilibrium after rescaling because it preserves force balance (assuming `scale_pressure=True`, but your example is a vacuum equilibrium so that is irrelevant anyways).

**Comment by YigitElma** [comment]
Hi @mohawk811 ! Thank you for your interest in DESC. I want to suggest you check [how to put code blocks on GitHub](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks). This way it would be easier for us to see your code in nice format. For example, your code will look like this,
```python
eq = get("precise_QA")
grid = LinearGrid(L=eq.L_grid, M=eq.M_grid, N=eq.N_grid, NFP=eq.NFP, rho=np.array([1.0]), sym=True)
# Define the major and minor radius
HBT_R0 = 1.0  # Major radius
HBT_a = 0.25  # Minor radius

# Define the Fourier coefficients for R (radial) and Z (vertical)
# In the old code, R_mn = [HBT_R0, HBT_a] corresponds to n=0, m=0 and n=0, m=1 modes
R_lmn = np.array([HBT_R0, HBT_a])  # Coefficients for R (radial direction, cosine modes)
Z_lmn = np.array([0.0, HBT_a])     # Coefficients for Z (vertical direction, sine mode for m=1)

# Define the mode numbers [m, n] for the Fourier terms
# Use positive for cosine modes and negative for sine modes
# R uses cosine modes: m=0, n=0 (constant) and m=1, n=0 (cosine term)
# Z uses sine modes: m=-1, n=0 for the sine term
modes_R = np.array([[0, 0], [1, 0]])  # Mode numbers for R (cosine modes)
modes_Z = np.array([[0, 0], [-1, 0]])  # Mode numbers for Z (sine mode for m=1)
```

**Comment by dpanici** [comment]
Is the vessel you are trying to fit into a fixed major radius R? If so, you may also need to increase the aspect ratio of your equilibrium. Our rescale utility assumes constant aspect ratio, but with that assumption you might not be able to fit this equilibrum into the vessel
