### ISSUE TITLE
Plasma Vessel distance objective help

### ISSUE THREAD

**Issue by mohawk811** [PlasmaControl/DESC#1328]
Hello!

Is there a way to use the plasma vessel distance penalty term where we have the plasma grid be a volume as opposed to just optimizing the boundary? I normally get a mismatch array issue

```
    grid2 = ConcentricGrid(
         L=eq.L_grid, M=eq.M_grid, N=eq.N_grid, NFP=eq.NFP, sym=True
    )
    grid1 = LinearGrid(
          M=eq.M_grid, N=eq.N_grid, NFP=eq.NFP, rho=np.array([1.0]), sym=True
    )

 PlasmaVesselDistance(surface=surf,eq=eq,bounds=(.05,1), surface_grid=grid1, plasma_grid=grid2, surface_fixed=True, weight=1, use_signed_distance=True),
```

**Comment by mohawk811** [comment]
The reason why is because I want to ensure that my plasma volume is properly force balanced

**Comment by dpanici** [comment]
I am unsure what you mean? the this objective if your boundary of your plasma is inside the vessel, then assuming your plasma is nested, the rest of the plasma should be in your vessel.

The grid used here for the plasma need not be the same grid used for ForceBalance in your constraints, and in fact should definitely not be. Is that the point of confusion?

**Comment by mohawk811** [comment]
This  makes sense. Thank you!
