### ISSUE TITLE
Notebook tests fail with `pytest-benchmark 5.0.0`

### ISSUE THREAD

**Issue by unalmis** [PlasmaControl/DESC#1333]
https://github.com/PlasmaControl/DESC/actions/runs/11567604447/job/32198430312?pr=1119

**Comment by YigitElma** [comment]
It started after last nights dependency cache renewal. Only the following packages are changed
![image](https://github.com/user-attachments/assets/cf4688ac-50b7-4036-9313-52f627e8f824)
I am pretty sure it is `pytest-benchmark`.

And what do you mean by "ci doesn't run notebooks anymore"? CI runs tests if the target branch is master.

**Comment by unalmis** [comment]
That was my guess because master was merged into #1327 after it was merged into other prs, yet #1327 didn't have this issue.

**Comment by YigitElma** [comment]
#1327 didn't have this because it didn't run any tests with updated dependencies (I mean newer versions of cached). I reran it now and it also has the same problem.
