### ISSUE TITLE
Add a check for the surface type in `from_input_file` by making sure `l` modes are all zero

### ISSUE THREAD

**Issue by dpanici** [PlasmaControl/DESC#1339]
>The non-zero l modes in the input file warning can be >added in some other PR. Seems fine to me

_Originally posted by @YigitElma in https://github.com/PlasmaControl/DESC/pull/1327#pullrequestreview-2406004396_

**Comment by f0uriest** [comment]
I don't think this is needed, see https://github.com/PlasmaControl/DESC/pull/1327#discussion_r1823612438
