### ISSUE TITLE
Document Units of `FourierCurrentPotential`

### ISSUE THREAD

**Issue by unalmis** [PlasmaControl/DESC#1351]
Would it be better to define $K = n \times \nabla \Phi / \mu_0$ where  $\Phi = \Phi_{sv}(\theta,\zeta) + G \zeta + I \theta$? Then

- The magnetic field $B_{\text{vacuum}} = \nabla  \Phi_{sv}$ is in tesla
- The toroidal and poloidal field currents $I$ and $G$ are tesla-meters, and correspond to `I` and `G` as defined in `data_index`.
- The surface current density $K$ is in amperes/meter, so you get the standard biot-savart surface current law.

Right now the user has to supply  $\Phi_{sv}$ in amperes, while $I$ and $G$ need to be supplied in units of $2\pi$ times amperes, which is awkward.

**Comment by unalmis** [comment]
Right now the user has to supply  $\Phi_{sv}$ in amperes, which is awkward

**Comment by dpanici** [comment]
I and G are not in 2pi amperes, I and G themselves are physically the net toroidal and poloidal currents (in Amperes) on the surface (I and G as defined in the formulation for the current potential here). The 2pi is just a unitless normalization (afaik)

**Comment by unalmis** [comment]
My issue is DESC actually defines it like like $\Phi \text{ amperes } = \Phi_{sv}(\theta,\zeta) \text{ amperes } + \frac{1}{2\pi} (\text{net poloidal current amperes} \zeta + \text{net toroidal current amperes} \theta)$. However it does not specify that the units anywhere and just states $\Phi = \Phi_{sv}(\theta,\zeta) + \frac{1}{2\pi} (G \zeta + I \theta)$. 

I don't like that because I expect a current potential to satisfy $B_{\text{vacuum}} = \nabla  \Phi_{sv}$ and hence expect $\Phi_{sv}$ to be in units of Tesla meters. Upon seeing the labels  `I` and `G` as defined elsewhere in DESC are tesla-meters, one can be misled into thinking $\Phi$ is tesla-meters.

**Comment by unalmis** [comment]
The $2\pi$ normalization disappears if you define $I$ and $G$ as i did in the first message.

**Comment by f0uriest** [comment]
Why is $B_{vac} = \nabla \Phi_{SC}$? that would be a magnetic scalar potential, not a current potential.

The current potential defines $K = n \times \nabla \Phi$

**Comment by unalmis** [comment]
Yes, $B_{\text{vacuum}} = \nabla  \Phi_{sv}$ is the magnetic scalar potential. Currently however,  the Fourier Current potential class defines $B_{\text{vacuum}} \mu_0 = \nabla  \Phi_{sv}$ and doesn't state the units.

**Comment by dpanici** [comment]
Resolved by #579
