### ISSUE TITLE
bounce integral of a omnigenity field

### ISSUE THREAD

**Issue by handi-h** [PlasmaControl/DESC#1357]
Hi, I am trying to use the difference of the adiabatic invariant J between equilibrium and omnigenity field as the lost function to optimize for omnigenity. And the bounce integral works well for equilibrium.
However, when I try to calculate the bounce integral of a omnigenity field, I replaced the data[“B”] from equilibrium with the `data1['|B|'] = field.compute([‘|B|’] , grid=grid, helicity=field.helicity)[‘|B|’]` while the grid is kept as `LinearGrid(rho=rho, M=eq0.M_grid, N=eq0.N_grid, NFP=eq0.NFP, sym=False)`. Besides, considering the required data for `bounce2d` has 'B^zeta' component, I have used `data1['B^zeta']=data1['|B|']*data['B^zeta']/data['|B|']`. The plot shows there is only 1 magnetic well for zeta from 0-2pi, while the bounce plot using equilibrium gives 4 as eq0.NFP=4. 
Do you know how to correct this issue or how to calculate the bounce integral of a omnigenity field with the equilibrium geometry?

<img width="555" alt="Screenshot 2024-11-11 at 3 25 11 PM" src="https://github.com/user-attachments/assets/f3d358f1-899f-4c9e-9afb-216102a869d3">
<img width="590" alt="Screenshot 2024-11-11 at 3 25 20 PM" src="https://github.com/user-attachments/assets/7e05866c-360b-45f0-bc99-2de34909fcba">

**Comment by unalmis** [comment]
Could you put together a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) demonstrating the issue? That will prevent us from having to guess at what the issue might be. Thanks!

**Comment by handi-h** [comment]
Thank you. This is the minimal example I created. The eq0 and field used here are from a previously stored case that I optimized following the Omnigenity Optimization instructions. I apologize for any confusion—please feel free to reach out if anything is unclear.
[bounce_integral.ipynb.zip](https://github.com/user-attachments/files/17709373/bounce_integral.ipynb.zip)

**Comment by unalmis** [comment]
Note that I don't have the equilibrium or the field, but based on the plots the fields differ somewhat.

1. Is there a reason the number of wells should match or is this just a heuristic expected from the plots?
2.  In the code you gave, `theta` is computed on the equilbrium field. This does a root finding  to identify the coordinates of the field lines for this equilibrium. Then when you feed the omnigenous fields B norm into the `Bounce2D` plotting routine, you use those same `theta` coordinates to specify the field lines of the omnigenous field. Since the field lines differ, these coordinates may not accurately specify the field lines of the omnigenous field.

**Comment by handi-h** [comment]
Thanks for your response.
1. To match their adiabatic invariant J for optimization, the wells shape should not have such a big difference in my opinion. Besides, the boozer plot also does not show such a big difference. For a NFP=4 field, following the magnetic field, 4 wells should be expected for the whole torus.
2. The direct assign of field to equilibrium must will arouse some discrepancies. I will appreciate it if you have any suggestions or direction to calculate J for omnigenity field.
If there are any issues with my understanding, I would greatly appreciate your clarification.

**Comment by handi-h** [comment]
I thought this should owing to the data input calculated from `field.compute([‘|B|’] , grid=grid, helicity=field.helicity)[‘|B|’]`
When I compare them in 2D plot using
```
A=grid.nodes
B1=eq0.compute(Bounce2D.required_names + ["min_tz |B|", "max_tz |B|"], grid=grid)["|B|"]
B2=field.compute(['|B|'] , grid=grid,helicity=field.helicity)['|B|']
x = A[:, 1]
y = A[:, 2]

fig, axes = plt.subplots(1, 2, figsize=(14, 6))

triang = tri.Triangulation(x, y)
contour1 = axes[0].tricontourf(triang, B1, cmap='viridis')
fig.colorbar(contour1, ax=axes[0], label='Value of B1')
axes[0].set_title('2D Color Map from B1')
axes[0].set_xlabel('A[:, 1]')
axes[0].set_ylabel('A[:, 2]')

contour2 = axes[1].tricontourf(triang, B2, cmap='viridis')
fig.colorbar(contour2, ax=axes[1], label='Value of B2')
axes[1].set_title('2D Color Map from B2')
axes[1].set_xlabel('A[:, 1]')
axes[1].set_ylabel('A[:, 2]')

plt.tight_layout()
plt.show()
```
it gives the figure like
![Screenshot 2024-11-12 095722](https://github.com/user-attachments/assets/153e1ab4-bf2a-4a21-80b9-e3868ee0ca14)
which does not look like in the (ρ,θ,ζ) coordinates space compared with the left figure compare, as their boozer_surface figure is very close. Could you tell me how to produce the data for omnigenous field with the same structure as equilibrium?
