### ISSUE TITLE
Rotating Equilibrium in Space

### ISSUE THREAD

**Issue by Taegeun-Jeong** [PlasmaControl/DESC#1368]
Hi All.

I have two different equilibria, and want to compare their boundaries using _plot_boundaries_, or _plot_comparison_, etc.
However their angle $\phi$ is not aligned each other, which makes it difficult for me to do it.

Can I rotate the equilibrium in space by 90 degress (pi/4) so that they are aligned with each other?

![image](https://github.com/user-attachments/assets/d2ce53c2-8770-4f94-af21-35fa59545724)

**Comment by f0uriest** [comment]
I vaguely recall @ddudt or @YigitElma had a utility for this?

**Comment by YigitElma** [comment]
I believe @ddudt added a function to flip $\theta$. I don't have a function for this but I can implement it if no one has since I sometimes need this kind of functionality.

**Comment by YigitElma** [comment]
Here is a code to rotate the equilibrium in $\zeta$ direction by $\pi/NFP$ degrees. 
```python
eq = get("precise_QH")
eq_rotated = eq.copy()
R_lmn = np.array(eq_rotated.R_lmn)
Z_lmn = np.array(eq_rotated.Z_lmn)
L_lmn = np.array(eq_rotated.L_lmn)
new_R_lmn = R_lmn.copy()
new_Z_lmn = Z_lmn.copy()
new_L_lmn = L_lmn.copy()

Rn_modes = np.array(eq.R_basis.modes[:, 2])
Zn_modes = np.array(eq.Z_basis.modes[:, 2])
Ln_modes = np.array(eq.L_basis.modes[:, 2])

new_R_lmn[Rn_modes%2 == 1] = -R_lmn[Rn_modes%2 == 1]
new_Z_lmn[Zn_modes%2 == 1] = -Z_lmn[Zn_modes%2 == 1]
new_L_lmn[Ln_modes%2 == 1] = -L_lmn[Ln_modes%2 == 1]

eq_rotated.R_lmn = new_R_lmn
eq_rotated.Z_lmn = new_Z_lmn
eq_rotated.L_lmn = new_L_lmn

eq_rotated.surface = eq_rotated.get_surface_at(rho=1.0)
eq_rotated.axis = eq_rotated.get_axis()

fig = plot_3d(eq,'|B|')
plot_3d(eq_rotated,'|B|', fig=fig)
```

I believe this should work for your equilibrium which has NFP=2. So, the total rotation is $\pi/4$ degrees. For general rotation, I might need to look at it more. And it might take a while to merge in master branch, so you can use this version for now.

**Comment by Taegeun-Jeong** [comment]
@dpanici @YigitElma Thanks a lot for your help! I've used that function in the `yge/rotate_zeta` branch, and it worked well. It's going to be very helpful for my research.
