### ISSUE TITLE
Improve Bounce tests

### ISSUE THREAD

**Issue by dpanici** [PlasmaControl/DESC#1398]
- [ ] https://github.com/PlasmaControl/DESC/blob/95612fa625bd5ba939569004c767ed02594586f0/tests/test_integrals.py#L1000

https://dlmf.nist.gov/19.7#E4

- [ ] https://github.com/PlasmaControl/DESC/blob/95612fa625bd5ba939569004c767ed02594586f0/tests/test_integrals.py#L1243

**Comment by unalmis** [comment]
I don't think this is necessary anymore since I wrote quadrature plots for wells with ripples and it works fine. Feel free to close
