### ISSUE TITLE
Apparent mismatch between ballooning objective output and direct calculation of growth rates

### ISSUE THREAD

**Issue by f0uriest** [PlasmaControl/DESC#1424]
setup:

```python

eq0 = desc.examples.get("HELIOTRON")

nalpha = 8  # Number of field lines

# Field lines on which to evaluate ballooning stability
alpha = np.linspace(0, np.pi, nalpha, endpoint=False)

# Number of toroidal transits of the field line
nturns = 3

# Number of point along a field line per transit
nzetaperturn = 200

rho=0.8

obj2 = desc.objectives.BallooningStability(
            eq=eq0,
            rho=rho,
            alpha=alpha,
            nturns=nturns,
            nzetaperturn=nzetaperturn,
            weight=1,
            target=0,
        )
obj2.build()
```

We expect the following 3 to give the same answer since the objective has target=0 and weight=1
```python
print(obj2.compute(eq0.params_dict, constants=obj2.constants))
print(obj2.compute_scaled_error(eq0.params_dict, constants=obj2.constants))
print(obj2.compute_scalar(eq0.params_dict, constants=obj2.constants))
```
which gives
```
221.8172472905935
[221.81724729]
221.81724729059223
```

which seems fine

But if we then compute the growth rates directly and apply the same reduction as in the objective function:

```python
# range of the ballooning coordinate zeta
zeta = np.linspace(-np.pi * nturns, np.pi * nturns, nzetaperturn*nturns)

grid = desc.grid.Grid.create_meshgrid(
    [rho, alpha, zeta], coordinates="raz", period=(np.inf, 2 * np.pi, np.inf)
)

# make sure its on the same points
np.testing.assert_allclose(alpha, obj2.constants['alpha'], atol=1e-14)
np.testing.assert_allclose(zeta, obj2.constants['zeta'], atol=1e-14)

ball_data0 = eq0.compute(["ideal ballooning lambda"], grid=grid)
lam = ball_data0["ideal ballooning lambda"]

# same as in obj2.compute
lambda0, w0, w1 = obj2.constants["lambda0"], obj2.constants["w0"], obj2.constants["w1"]

# Shifted ReLU operation
data = (lam - lambda0) * (lam >= lambda0)

results = w0 * np.sum(data) + w1 * np.max(data)
print(results)
```

gives 
```
14.325405153826495
```

which is way smaller. Am I missing something?

**Comment by rahulgaur104** [comment]
Different normalizations due to different values of data["a"]
For the first case it's 1.506 and
for the second case it's 0.95
which causes all the coefficients to change by a constant factor.
I think the second one is wrong and we need to explicitly provide data["a"] to the compute function.

**Comment by rahulgaur104** [comment]
Actually the data["a"] in the objective is incorrect and I can't figure out why.
When I do 
`eq.compute("a", grid=LinearGrid(rho=1.0, M=eq.M_grid, N=eq.N_grid, NFP=eq.NFP))[["a"]`
I get the right answer but when I print 
`compute_fun(eq, ["a"], params=params, transforms=constants["len_transforms"], profiles=constants["len_profiles"])["a"]`
which is exactly what is happening in the BallooningStability objective, I get a wrong value. I don't know why this is happening.

**Comment by f0uriest** [comment]
I thought stuff like `a` should be computed on a quadrature grid, not a single surface grid? I think in `eq.compute` we override the user grid to do that, so that's likely why its giving a different answer. If that's the case the fix would just be to use a quadrature grid for `len_transforms` etc, but I thought there was some reason we didn't do that originally?

**Comment by rahulgaur104** [comment]
What I mean by "a"  the effective minor radius which only depends on the boundary shape. Why would it need a quadrature(volume) grid? We just calculate the effective A(z) on the boundary  and from that, calculate "a".
Also, a quadrature grid will never have rho points exactly on the boundary, right?

**Comment by f0uriest** [comment]
`A(z)` for an equilibrium is computed as a surface integral over the cross section, not a boundary integral:

https://github.com/PlasmaControl/DESC/blob/4fd41f161ba2bc397454085521011dda316ecb27/desc/compute/_geometry.py#L154-L180

I think to only use a boundary grid needs #1094

**Comment by rahulgaur104** [comment]
Ok, then let me use quadrature grid for "a" inside the objective. For calculating the eigenvalue using eq.compute, I'll pass "a" as data computed on a quadrature grid.

**Comment by unalmis** [comment]
The documentation for adding objectives would benefit from a section that tells the developer to make sure their dependencies are computed on the right grids, as it is not done automatically as is done through `eq.compute`.
