### ISSUE TITLE
Linux Mint 21.3 laptop pip install issues. Various modules not found.

### ISSUE THREAD

**Issue by daringli** [PlasmaControl/DESC#1431]
I'm running into numerous problems trying to
`pip install desc` **UPDATE: THIS IS A MISTAKE**
on my laptop.

**UPDATE: I accidentally did `'pip install desc` and not `pip install desc-opt`. If you found this issue by searching for keras or tensorflow in the issue tracker, you might have done the same mistake.**

1. pip fails to install Multicore-TSNE. If I clone from https://github.com/DmitryUlyanov/Multicore-TSNE and` pip install .`, it works.
2. scanpy.api not found. If I change from `import scanpy.api as sc` to `import scanpy as sc`, it works.
3. Various keras problems. For example `No module named 'keras.engine'`. There are many errors here and I haven't resolved all of them.
4. `from SAE import SAE` gives a `ModuleNotFoundError`. Might be related to other errors since the keras errors are not resolved.

Any ideas?

I'm using:
keras version 3.7.0
tensorflow 2.18.0
scanpy 1.10.4
numpy 1.26.4
jax 0.4.26
Many of these were probably installed by pip installing desc-opt.

**Comment by dpanici** [comment]
Hi! So a couple points/questions
- what OS are you using?
- keras/tensorflow are not required by desc-opt afaik (I also don't know what SAE is or Multicore-TSNE tbh), can you try pip installing inside of a clean conda environment?

**Comment by daringli** [comment]
Thanks for the quick reply. OS is Linux Mint 21.3, so basically Ubuntu 22.04.3.

> keras/tensorflow are not required by desc-opt afaik
This was a big red flag. I think what must have happened is that I've installed 'desc' and not 'desc-opt'.
https://pypi.org/project/desc/
It seems likely based on the project description. Excitingly, both desc and desc-opt packages write to `~/.local/lib/python3.10/site-packages/desc`, so I probably have a very dirty install by now.

With this, I think you can close the issue.
Hopefully, it'll be helpful if someone does the same mistake and searches in the issue tracker to see if it's a known problem. (Or it's at least good for a laugh. Sorry for wasting your time!)

**Comment by daringli** [comment]
Issue was due to installing pip package `desc` not `desc-opt`, which is a different code.

**Comment by dpanici** [comment]
Ah yes the similar name is unfortunate, and the same package directory name doubly so, let us know if any issues relating to desc-opt arise though!
