### ISSUE TITLE
Basic Equilibrium tutorial

### ISSUE THREAD

**Issue by Kr246893** [PlasmaControl/DESC#1432]
Ran the basic equilibrium tutorial and got the following errors.

1. desc.io.load
```
eq_fam = desc.io.load("input.HELIOTRON_output.h5")
print("Number of equilibria in the EquilibriaFamily:", len(eq_fam))
fig, ax = plot_comparison(
    eqs=[eq_fam[1], eq_fam[3], eq_fam[-1]],
    labels=[
        "Axisymmetric w/o pressure",
        "Axisymmetric w/ pressure",
        "Nonaxisymmetric w/ pressure",
    ],
)
```

got this error:
```---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
Cell In[8], line 1
----> 1 eq_fam = desc.io.load("input.HELIOTRON_output.h5")
      2 print("Number of equilibria in the EquilibriaFamily:", len(eq_fam))
      3 fig, ax = plot_comparison(
      4     eqs=[eq_fam[1], eq_fam[3], eq_fam[-1]],
      5     labels=[
   (...)
      9     ],
     10 )

File ~/anaconda3/envs/desc-env/lib/python3.9/site-packages/desc/io/optimizable_io.py:59, in load(load_from, file_format)
     57         obj = pickle.load(f)
     58 elif file_format == "hdf5":
---> 59     with h5py.File(load_from, "r") as f:
     60         if "__class__" in f.keys():
     61             cls_name = f["__class__"][()].decode("utf-8")
```

specifying the input directory resolves this error
```
eq_fam = desc.io.load("/../.../DESC/desc/examples/HELIOTRON_output.h5")
print("Number of equilibria in the EquilibriaFamily:", len(eq_fam))
fig, ax = plot_comparison(
    eqs=[eq_fam[1], eq_fam[3], eq_fam[-1]],
    labels=[
        "Axisymmetric w/o pressure",
        "Axisymmetric w/ pressure",
        "Nonaxisymmetric w/ pressure",
    ],
)
```
``` 
Number of equilibria in the EquilibriaFamily: 3
```
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In[9], line 4
      1 eq_fam = desc.io.load("/.../../DESC/desc/examples/HELIOTRON_output.h5")
      2 print("Number of equilibria in the EquilibriaFamily:", len(eq_fam))
      3 fig, ax = plot_comparison(
----> 4     eqs=[eq_fam[1], eq_fam[3], eq_fam[-1]],
      5     labels=[
      6         "Axisymmetric w/o pressure",
      7         "Axisymmetric w/ pressure",
      8         "Nonaxisymmetric w/ pressure",
      9     ],
     10 )

File ~/anaconda3/envs/desc-env/lib/python3.9/site-packages/desc/equilibrium/equilibrium.py:2554, in EquilibriaFamily.__getitem__(self, i)
   2553 def __getitem__(self, i):
-> 2554     return self._equilibria[i]

IndexError: list index out of range
```
2.  Number of equilibria 3 , however in the tutorial it is 8. I wonder why ??
3. Unable to plot.

**Comment by dpanici** [comment]
This is a bit confusing, so `input.HELIOTRON_output.h5` should be in the same [directory](https://github.com/PlasmaControl/DESC/tree/master/docs/notebooks/tutorials) as the basic equilibrium tutorial. Can you `ls` inside your `DESC/docs/notebooks/tutorials` directory and see if that file is missing? I don't know how the file would be missing if you have a locally cloned repo, but loading in the correct file should solve your points 2. and 3. (as that file has 8 equilibria and so you won't get any indexing errors)

**Comment by Kr246893** [comment]
okay, basic question what is the difference between both these files ``input.HELIOTRON_output.h5`` in the ``DESC/docs/notebooks/tutorials`` folder and `` HELIOTRON_output.h5`` in the ``DESC/desc/examples`` folder.

**Comment by YigitElma** [comment]
> okay, basic question what is the difference between both these files `input.HELIOTRON_output.h5` in the `DESC/docs/notebooks/tutorials` folder and ` HELIOTRON_output.h5` in the `DESC/desc/examples` folder.

As discussed previously on the same documentation [here](https://desc-docs.readthedocs.io/en/latest/notebooks/tutorials/basic_equilibrium.html#Running-DESC-from-a-VMEC-input), the file `input.HELIOTRON_output.h5` is generated from a VMEC input file (`input.HELIOTRON` file in the same directory). Once you run the documented command,
```
python -m desc -vv input.HELIOTRON -o input.HELIOTRON_output.h5`
```
It will take `input.HELIOTRON` file, convert it to DESC input file (`input.HELIOTRON_desc` in the same directory) and then solve the equilibrium.

The `.h5` file in the examples folder has different solver options.
