### ISSUE TITLE
Address possible breaking changes from `jax==0.4.36`

### ISSUE THREAD

**Issue by dpanici** [PlasmaControl/DESC#1434]
[Just released yesterday](https://github.com/jax-ml/jax/releases/tag/jax-v0.4.36) and coincides with our CI failing mysterously, so we need a PR to address these changes or limit the JAX upper version (ideally the former)

Seemingly related to `interp1d`calls from  interpax, though a simple call to `interp1d` from interpax and the newest JAX does not return the error so it must be something specific with how we are using it

**Comment by f0uriest** [comment]
Most of that issues look like they might be fixed upstream in equinox: https://github.com/patrick-kidger/equinox/pull/907

**Comment by f0uriest** [comment]
Looks like its actually due to https://github.com/jax-ml/jax/issues/25329
