### ISSUE TITLE
Adding equilibrium in desc/examples

### ISSUE THREAD

**Issue by aknath23** [PlasmaControl/DESC#1437]
Is it possible to add equilibrium in desc/examples so that i can get the equilibrium uising 
```
eq = desc.examples.get("XXXX")
```
i created  ``XXXX `` file in the desc/examples and converted it to ``XXXX_output.h5 ``  but i am getting this error

```
ValueError: example XXXX not found, should be one of ['DSHAPE', 'precise_QA', 'HELIOTRON', 'NCSX', 'ARIES-CS', 'ESTELL', 'precise_QH', 'DSHAPE_CURRENT', 'ATF', 'SOLOVEV', 'WISTELL-A', 'W7-X', 'HSX']
```

**Comment by YigitElma** [comment]
If you just want to load an equilibrium, you can just use `desc.io.load`. Here is how to use it.
https://desc-docs.readthedocs.io/en/latest/notebooks/tutorials/use_outputs.html#Loading-in-a-DESC-Equilibrium

I don't know why when you add the output file to the directory of `desc/examples`, you cannot use `get` with it. Maybe you should restart your kernel? Or if you also installed DESC with `pip install desc-opt` you are importing that DESC and your changes to the cloned repository is not reflected.

Why do you need to use `desc.examples.get` specifically?
