### ISSUE TITLE
Dictionary for reverse mode lookup

### ISSUE THREAD

**Issue by f0uriest** [PlasmaControl/DESC#144]
We should redo this method:

https://github.com/PlasmaControl/DESC/blob/9f1427cbfc6df9e6dfb2407258996dadc6882d1b/desc/basis.py#L46

to just use a dictionary so its compatible with JIT

**Comment by ddudt** [comment]
Resolved by 7ec3cc8e08aac605c3729beb2beb4646198a9743, but could be improved. The original implementation allowed for arrays of mode numbers, while this solution can only be used for a single index. But it works with JIT, and the latest compute functions only ever need a single index at a time.

**Comment by f0uriest** [comment]
I think it should be possible to use something like what we have now with clever masking and logical indexing such that it works with jit. The size of the output is determined by the size of the input.
