### ISSUE TITLE
DESC objectives branch currently not Finding GPU on Traverse

### ISSUE THREAD

**Issue by dpanici** [PlasmaControl/DESC#145]
Current objectives branch #126  does not find the GPU when ran on a GPU node on Traverse:
`2022-02-17 19:30:21.846425: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
DESC version 0.4.12+238.ge20a5df, using JAX backend, jax version=0.2.19, jaxlib version=0.1.71, dtype=float64
Using device: CPU, with 286.34 GB available memory
/home/dpanici/DESC/desc/__init__.py:74: UserWarning: CUDA_VISIBLE_DEVICES= did not match any physical GPU (id=['0']), falling back to CPU`

The last commit on this branch that was working with the GPU is d880a8d6.
The next commit, 25d6006f, did not touch the backend.py file, but did introduce an import jnp statement in utils.py that may be an issue with a circular import possibly?

**Comment by ddudt** [comment]
Fixed by 0fcc7085f3394f085c1a796a50f996770adc8adf.
