### ISSUE TITLE
Include gauge freedom, poincare BC constraints on objectives branch

### ISSUE THREAD

**Issue by f0uriest** [PlasmaControl/DESC#170]
- [x] Right now we don't enforce the gauge freedom/axis condition on lambda in the objectives branch (which is fine for symmetric equilibria), so we need to add another linear objective to handle that

- [x] Also would be good to implement the poincare BC.

For both we can mostly port code from master, and reuse stuff from the ``LCFSBoundary`` class

**Comment by dpanici** [comment]
#193 implemented the Poincare BC. gauge freedom still not implemented right now

**Comment by dpanici** [comment]
#200  incorporated the gauge freedom in objectives branch, which was merged to master in #126 

Poincare BC is in its own PR in #205 for now
