### ISSUE TITLE
Add Conservative default settings for continuation method?

### ISSUE THREAD

**Issue by f0uriest** [PlasmaControl/DESC#2]
What are good paramters for resolution & ratios during a multistep solution?

**Comment by f0uriest** [comment]
After a fair amount of testing, it seems like `ftol=1e-4` and `nfev=50` is pretty reasonable. Going for tighter tolerances and more iterations can get to lower error, but the rate of convergence slows down a lot so its usually better to go for fewer iterations per step and more resolution steps to get to higher resolution. This also helps to avoid overfitting the basis.

For perturbations, its usually best to start from a vacuum tokamak, then increase pressure, then perturb into a stellarator. The size of the perturbation steps depends somewhat on how "complicated" the perturbations are, but steps of 0.25 seems fairly conservative. For simple cases you can do that full perturbation in 1 step.

**Comment by dpanici** [comment]
We could add default continuation steps to input files that are generated from a VMEC input for highly shaped/ high resolution cases?
