### ISSUE TITLE
Add a utility function to load the boundary from an input file, or to create an `Equilibrium` or `EquilibriaFamily` with the parameters outlined in an input file (resolution, boundary, etc)

### ISSUE THREAD

**Issue by f0uriest** [PlasmaControl/DESC#214]

**Comment by f0uriest** [comment]
what about letting you create an Equilibrium directly from a file path?
then you could do `surf = Equilibrium(path).surface`` ? that would be more general I think

**Comment by f0uriest** [comment]
but in general id prefer to move away from text input files etc

**Comment by dpanici** [comment]
Yes that is probably better. I agree but people have other codes which output fourier harmonics as text files for VMEC so it is probably good to support that still
