### ISSUE TITLE
Add initial guesses for solutions using Qsc?

### ISSUE THREAD

**Issue by dpanici** [PlasmaControl/DESC#220]
For fixed bdry, could take Qsc solution out to rho=0.3 or 0.4 and then scale to the boundary

**Comment by dpanici** [comment]
Could be something like initial_guess('Qsc',until_rho=0.3) which would construct the guess from the axis and use the solution surfaces up until rho=0.4 or 0.5 and then linearly scale that 0.3 surface to the boundary (since it seems that the surfaces shape is very close to the solution until s=0.3 and rho = sqrt(s) so rho ~ 0.5)

**Comment by f0uriest** [comment]
I sort of had this in mind when I added ``Equilibrium.set_initial_guess``, one of the options is to give R,Z at a set of flux coordinates, so we could probably use that.

**Comment by ddudt** [comment]
Also from Qic. They both use the same conversion to a VMEC input file that we could easily adapt to work with DESC: [Qsc.to_vmec()](https://github.com/landreman/pyQSC/blob/main/qsc/to_vmec.py) & [Qic.to_vmec()](https://github.com/rogeriojorge/pyQIC/blob/main/qic/to_vmec.py).
