### ISSUE TITLE
Add Jacobian Sign Change as test of unestedness

### ISSUE THREAD

**Issue by dpanici** [PlasmaControl/DESC#240]
Currently we check for nested surfaces during the equilibrium solve with the `is_nested` method of equilibrium which checks the geometry of a given number of flux surfaces. However a faster way would be to just check that the sign of the jacobian is only one value (if there is a sign change, that means jacobian is zero somewhere and thus we have unnested surfaces.

todo:

- [ ] Implement jacobian sign change in optimizer callback function to exit early if unnested surfaces detected, and to check for surface nestedness after a perturbation
- [ ] check that the optimizer cannot recover from unnested surfaces once they happen in the optimization (gut feeling is no but is easy to check if can find an example where we go unnested during the minimization)

**Comment by f0uriest** [comment]
Closing this after merging #243
