### ISSUE TITLE
VMEC to DESC input file conversion for toroidal current constrained cases

### ISSUE THREAD

**Issue by dpanici** [PlasmaControl/DESC#241]
[By default](https://github.com/jonathanschilling/educational_VMEC/blob/0999e1e66d0ba8407e587084787cbf0d92c8dab2/src/profile_functions.f#L305), VMEC `AC` coefficients constrain the radial derivative of the net enclosed toroidal current. So, when converting a VMEC to DESC input file, we need to also check for `pcurr_type` and [change the conversion accordingly](https://github.com/hiddenSymmetries/VMEC2000/blob/e5de70486235be997e95ca4a129441d51b796226/Sources/Input_Output/readin.f#L128), integrating in `s` if it is the default `power_series` or if `pcurr_type` is not specified at all

also need to ensure we read in the `CURTOR` parameter, which is an overall scale factor (in Amps) on the enclosed net toroidal current profile (so by default NOT a scale factor on the `AC` coefficients directly, as those describe `I'(s)`). [See here](https://github.com/jonathanschilling/educational_VMEC/blob/7ce6c6093a3adf06c8cb37681b6ea81549632c87/src/profil1d.f90#L81) for multiplication, where `currv = mu0*curtor` as [seen here](https://github.com/jonathanschilling/educational_VMEC/blob/fbdebe2a4324573f5763b6a2c1ad8d8d8a20ca2c/src/readin.f90#L84)

related to #69

**Comment by f0uriest** [comment]
if the default for vmec is in terms of ``I'`` would it make sense for us to use that as well? It's trivial to integrate, and doing it that way would make sure the user doesnt give a profile with nonzero current on axis

**Comment by unalmis** [comment]
Also when symmetry is off in VMEC input, DESC converts this to `sym = False`. The resulting input file will not run. DESC should instead convert this to `sym = 0`. And we should stop the warning that iota is not specified in fixed current mode. `RuntimeWarning: Save attribute '_iota' was not saved as it does not exist.`

**Comment by f0uriest** [comment]
I think I fixed the symmetry thing in the latest update to master, you might just need to rebase.

**Comment by f0uriest** [comment]
could make curtor something like pres_scale also

**Comment by dpanici** [comment]
@unalmis I forget, how did we resolve this? I don't think we actually integrate the current profile parameters when we read in a VMEC input file, so I think we handle this incorrectly right now

**Comment by unalmis** [comment]
I checked the code again and it looks fine to me. https://github.com/PlasmaControl/DESC/blob/8d2b96f0bcc8cf9f835b0d4eb71bc4d0184a0d53/desc/io/input_reader.py#L1592

Here's the math that describes what's going on. For the last part we scale so that the total enclosed current (`I` at rho = 1) is equal to the value of `curr_torr`.
![curr_torr](https://github.com/PlasmaControl/DESC/assets/98659578/5df72de0-c8c3-4ddc-9f47-cd9e9ec38a3b)

Do we need to do this somewhere else too?

**Comment by unalmis** [comment]
I don't understand why we added the `or 1` in a later commit.
https://github.com/PlasmaControl/DESC/blob/8d2b96f0bcc8cf9f835b0d4eb71bc4d0184a0d53/desc/io/input_reader.py#L1604
I read this line as
`curr_tor / (int(bool(some_number) or bool(1)) = curr_tor / int(True) = curr_tor`. So the end result is we didn't divide by the sum like we wanted to. Is this the issue?

**Comment by dpanici** [comment]
hm wait I somehow missed these lines. I was running into issues when running a VMEC input file with current but maybe let me just double chekc this tomorrow and see if I was not just doing something incorrectly

**Comment by dpanici** [comment]
I think issue was that we dont support if AC or AM are provided like
```
AC(0)=XXX
AC(1)=XXX
```
instead of `AC = XXX XXX`
so I think that was actually my issue

**Comment by f0uriest** [comment]
> I don't understand why we added the `or 1` in a later commit.
> 
> https://github.com/PlasmaControl/DESC/blob/8d2b96f0bcc8cf9f835b0d4eb71bc4d0184a0d53/desc/io/input_reader.py#L1604
> 
> I read this line as
> 
> ```python
> curr_tor / int(bool(some_number) or bool(1)) = curr_tor / int(True) = curr_tor
> ```
> 
> So the end result is we didn't divide by the sum like we wanted to. Is this the issue?

The `or 1` was added to avoid division by zero, it's basically equivalent to `np.sum(foo) if np.sum(foo) !=0 else 1`
See https://en.wikipedia.org/wiki/Null_coalescing_operator#Python
