### ISSUE TITLE
Make sure all plot functions take in basic kwargs like figsize, fontsize etc

### ISSUE THREAD

**Issue by dpanici** [PlasmaControl/DESC#244]
Currently not all plotting functions take in useful kwargs that others do, making it confusing when a kwarg is passed and then nothing happens (namely the boozer plotting fxns). Should add these kwargs to all plotting functions 

related to #178

**Comment by dpanici** [comment]
Aditionally should throw a warning when some kwargs are unused to let the user know

**Comment by f0uriest** [comment]
Closing this after #245
