### ISSUE TITLE
plot_1d improvement

### ISSUE THREAD

**Issue by unalmis** [PlasmaControl/DESC#249]
I'd expect `desc.plotting.plot_1d` to plot any 1d quantity, not just those that can be evaluated on 1d linear grids.

I'm not aware of a way to plot 1d quantities computed on normal grids through DESC. `desc.plotting.plot_fsa` doesn't fill this need because it computes the flux-surface average of the given quantity with `sqrt(g)` when it's not always desired.

To plot `data["I"]`, the cleanest way (after `mercier` is merged to `master`) is:
```
def get_plot_data():
    # use the desc.compute.utils.compress function which is not in public docs
    x = compress(grid, eq.compute("rho", grid)["rho"])
    y = compress(grid, eq.compute("I", grid)["I"])
    return x, y
# make custom plots
```
We should add a function or modify `plot_1d` so that a user can do `plot_1d(eq, "I")` and get what they expect.

**Comment by unalmis** [comment]
We had discussed improving the dimension field in `data_index` to better specify the true length of quantities.
```
len(data["V"]) = 1
len(data["I"]) = number of surfaces
len(data["|B|"]) = number of nodes
```
This may be needed for a good fix to this issue. I can do this PR next month. If anyone needs it before, feel free to do it.

**Comment by dpanici** [comment]
- [ ] add (rho,theta,zeta) dep (field ["function of"]= ["r","t","z"] where if it is just ["r"] it is fxn of just r, etc) and global fxns are fxns of nothing so an empty list []
- [ ] add check in plot_1d if fxn of just rho, if so have it do an FSA and use plot_fsa (need to check that it is plotting against rho though) call fsa here with a kwarg like "use_sqrt_g=false" to avoid using 1/<sqrt(g)>
- [ ] add kwarg in fsa "use_sqrt_g=false"
