### ISSUE TITLE
Update Docs for VMEC Input File Conversion

### ISSUE THREAD

**Issue by dpanici** [PlasmaControl/DESC#264]
Note to update the[ docs for the input file converter ](https://desc-docs.readthedocs.io/en/latest/input.html#vmec-inputs)for VMEC to DESC, specifically to say that it will now include default continuation per #246 , and update the converted input file to reflect this as well

**Comment by dpanici** [comment]
Also add `.lower()` to `words[0]` inside of `input_reader.py` to handle input args that are just different cases (like `ANSI` instead of `ansi`)

**Comment by dpanici** [comment]
#261 addresses these

**Comment by unalmis** [comment]
The notebooks needed modification to run in #251 . I updated the 00 tutorial substantially as DESC now does automatic continuation on vmec input file conversion. Feel free to change it of course.
