### ISSUE TITLE
Profile different options for surface averages, compress/expand operations

### ISSUE THREAD

**Issue by f0uriest** [PlasmaControl/DESC#271]
There are a few different ways to do surface averaging operations and compress/expanding values to the full grid. We should test and profile different options (both for the forward computation and the jacobian, when used in the full end to end calculation)

- [x] Indexing with grid.unique_rho_idx etc
- [x] Precomputed matrices - ie, surface_average(x) = A*x, expand(x) = P*x
- [x] Histogram method
- [x] For loop
- [x] possibly others.

Another idea: make compress/expand etc methods of grid class?

**Comment by unalmis** [comment]
Linking the [loop algorithm](https://github.com/PlasmaControl/DESC/blob/3e1220a6e9db85bc039b53dd5fc20245701ab7b7/tests/test_compute_utils.py#L14). Should try jax style for loop though.
