### ISSUE TITLE
Inconsistent argument type for `optimizer` in `eq.solve` and `eq.optimize`

### ISSUE THREAD

**Issue by dpanici** [PlasmaControl/DESC#313]
in `eq.solve`, it can be a string or an optimizer, but in `eq.optimize` it must be an optimizer.

I would like both to be strings or optimizers so that you can pass in "dogleg" or whatever and have it work without an extra line making the optimizer. But I know passing in Optimizer objects lets you potentailly reuse it. 

How advantageous is reusing the Optimizer object? Is it so useful that we must require Optimizers to be passed? or can we allow string names as well to be passed?

**Comment by f0uriest** [comment]
Yeah that's just an inconsistent API, they should both be able to take either strings or ``Optimizer`` instances. I'll fix it
