### ISSUE TITLE
Profile Equilibrium init and try to speed it up

### ISSUE THREAD

**Issue by f0uriest** [PlasmaControl/DESC#342]
Just creating an Equilibrium object can be rather slow at high resolution (takes a few seconds, which feels slow for something that isn't really doing any serious math). @MothVine can you take a look and see if there are any obvious bottlenecks?

Example from our benchmarks:
https://github.com/PlasmaControl/DESC/blob/062767947e4056cca4546b09488164faf6d8a42e/tests/benchmarks/benchmark_cpu_small.py#L102

**Comment by MothVine** [comment]
Here's a profile of a simple L=M=N=5 equilibrium object being instanced, and a trace of the calls executed, looking in to it
![EQinit](https://user-images.githubusercontent.com/100051126/206560092-b7243c95-ac58-4073-84c9-30b93a8d7dd6.png)
[trace_report_EQinit.txt](https://github.com/PlasmaControl/DESC/files/10189222/trace_report_EQinit.txt)
