### ISSUE TITLE
Clean up docs

### ISSUE THREAD

**Issue by f0uriest** [PlasmaControl/DESC#365]
There are a couple of things in the code that aren't included in the online docs, and some things get formatted weird. We should at least make sure the docs build without throwing warnings (and then make RTD fail on warning) but would also be good to look through everything manually and make sure it looks correct.

**Comment by dpanici** [comment]
- [ ] reading in an input file using a python script
- [ ] specifying that the plain-text input is ONLY for equilibrum solving, not optimizing equilbria
- [ ] examples of optimization with different targets (make a more succinct optimization tutorial using individual objectives?) focusing less on building the equilibrium
