### ISSUE TITLE
Throw warning when computing FSA qtys with insufficient number of points

### ISSUE THREAD

**Issue by f0uriest** [PlasmaControl/DESC#438]
Just to let people know the results may be wrong if there's only 1 pt in the grid for example.

Not sure the best place is, easiest would probably be in compute.compute but could also move it lower to the surface average function itself so it only throws the error when it really means to?

**Comment by dpanici** [comment]
surface average function is probably the best place for it I think, I agree

**Comment by f0uriest** [comment]
My only worry is that the surface average function doesn't know anything about the underlying equilibrium or its resolution, so there's not an easy way to know how many nodes are "enough"

**Comment by f0uriest** [comment]
Better option:

in eq.compute, first check what qtys are volume or surface avgs. Compute those first on the correct grids, then initialize the data dict with those for the subsequent other calculations.
