### ISSUE TITLE
Add derivatives of metric tensor elements for Laplace's equation

### ISSUE THREAD

**Issue by f0uriest** [PlasmaControl/DESC#447]
For some of the coil/LM stuff that Francisco is doing he needs to solve Laplace's equation on a toroidal surface. In general curvilinear coordinates:
![image](https://user-images.githubusercontent.com/22567458/223468451-16d1386f-1c1f-416c-bfa7-1dd2e24c5603.png)

We have pretty much all the needed terms there except for the very last one, $\frac{\partial g^{ij}}{\partial x^i}$, but if we do it out we get:
![image](https://user-images.githubusercontent.com/22567458/224025490-25c3c4f3-10e9-43bc-957e-c7a1e41e7e35.png)
which I think is all stuff we have. (would appreciate someone checking my math on the above).

**Comment by unalmis** [comment]
i think you dropped a negative sign on the root g squared factor
