### ISSUE TITLE
Make objectives for coils

### ISSUE THREAD

**Issue by f0uriest** [PlasmaControl/DESC#496]
- [x] #901
  - [ ] Shape Gradient ([link](https://arxiv.org/pdf/1910.14144.pdf), [another link](https://iopscience.iop.org/article/10.1088/1741-4326/aac1c7), [one more link](https://arxiv.org/pdf/1910.14144.pdf), [final one](https://www.cambridge.org/core/journals/journal-of-plasma-physics/article/computing-the-shape-gradient-of-stellarator-coil-complexity-with-respect-to-the-plasma-boundary/8A0ED88DD11BEA08C92B45B175A50DDE))  
- [x] #895
- [x] #896
- [x] #897
- [x] #898
- [ ] #899
- [x] #900
- [x] #1111

**Comment by dpanici** [comment]
duplicate with #899
