### ISSUE TITLE
eq.solved = False when max iterations reached

### ISSUE THREAD

**Issue by ddudt** [PlasmaControl/DESC#502]
If `eq.solve` terminates because it reaches the maximum iteration limit, then the Equilibrium gets assigned the attribute `eq.solved = False`. However, it could still be a good equilibrium solution in this case. This can be problematic when saving the equilibrium as a wout file for use with external codes, since the wout property is assigned as `ier_flag = not eq.solved`. It should be noted that even when the optimization terminates "successfully" and assigns `eq.solved = True`, this does not guarantee that the solution is in fact a good equilibrium. 

Potential solutions:

1. Remove the `Equilibrium.solved` attribute and always output `ier_flag = False` in the wout files. This puts more burden on the user to check that they have a good solution, but avoids input/output errors with other codes. 
2. Change the `Equilibrium.solved` property to always check the volume averaged normalized force balance error against some threshold. This would always return the desired result, at the cost of requiring an extra computation every time it is called.

**Comment by f0uriest** [comment]
I'm starting to lean towards just getting rid of the `solved` attribute and always outputting `ier_flag=False` in the wout, any other ideas?

**Comment by f0uriest** [comment]
Resolved by #554
