### ISSUE TITLE
Make plotting grids more intuitive

### ISSUE THREAD

**Issue by f0uriest** [PlasmaControl/DESC#506]
This came up when I was helping Alan with some stuff:

- The `plot_boozer_modes` function has a default grid at `rho=1`, this works well. However if we want to plot boozer modes on an inner surface we have to create a grid with the right resolution, and there are different grids for plotting vs computing etc.
- Might be better to have an argument for `rho` and then the grid is made from that automatically, sort of how we have `phi` as an argument for `plot_section`. We would still have `grid` as a kwarg or something for full customization, but this would make common use cases easier.

**Comment by ddudt** [comment]
I already did this for `blot_boozer_modes` on the `omnigenity` [branch](https://github.com/PlasmaControl/DESC/blob/dd/omnigenity/desc/plotting.py#L2224)

**Comment by f0uriest** [comment]
...something something something about self contained feature branches...

**Comment by f0uriest** [comment]
Resolved by #549
