### ISSUE TITLE
Make keywords to solve methods uniform

### ISSUE THREAD

**Issue by dpanici** [PlasmaControl/DESC#510]
currently, `eq.solve`  takes `maxiter` but not `nfev`, but `solve_continuation` takes `nfev`. We should unify these APIs

**Comment by f0uriest** [comment]
I agree, we should fix this. Right now they're used somewhat interchangeably in many places, but they shouldn't be. In all of the optimizers that we have so far, one iteration means one accepted step by the optimizer, which may need more than 1 function evaluation. Generally each iteration requires one evaluation and factorization of the jacobian/hessian, which is the primary cost of the optimization, so iterations also correspond more closely to time. To me it makes sense to have the primary thing be `maxiter`, but right now the input file only has `nfev` so thats the main place we'd need to change it, but not sure the best way. Do we want to allow both? Or throw deprecation warnings etc?

**Comment by dpanici** [comment]
- [ ] change input file to use maxiter not nfev (add some backwards compat to read nfev as maxiter though? throw FutureWarning?)
