### ISSUE TITLE
Save Equilibrium grid solved with in the .h5 file

### ISSUE THREAD

**Issue by dpanici** [PlasmaControl/DESC#511]
currently when we save a equilibrium, its grid is not saved, which means when you load it you don't actually have the grid it was solved or saved with. We should have this as save attribute so that one has more information on how the equilibrium was solved

**Comment by f0uriest** [comment]
This might be tricky, as the grid is an attribute of the `Objective`, not the equilibrium. But assuming you used the default grid, wouldn't `L_grid, M_grid, N_grid, node_pattern` be enough?

**Comment by dpanici** [comment]
Right but sometimes the default grid wasn't used, which can then make it misleading when the equilibrium is loaded, and the solution is not the solution from the default grid. This happens when I run higher-resolution equilibria, where the default grid would be pretty large, so I use a smaller grid.

Also, the default grid when you create an equilibrium is 1.5* LMN (for ANSI), but from an input file if you don't specify grid resolutions the [default grid is 2*LMN ](https://github.com/PlasmaControl/DESC/blob/5edf6b419b08c49144dd213f1cb202f86765b4b7/desc/io/input_reader.py#L597), so this can cause an additional source of mismatch when you load in an equilibrium solved from an input file

**Comment by f0uriest** [comment]
@dpanici can we close this?

**Comment by dpanici** [comment]
Yea, I think I just must have been doing something incorrect, I think the IO attributes are enough for what I was worried about.
