### ISSUE TITLE
Make Example equilibria consistent with their input files

### ISSUE THREAD

**Issue by dpanici** [PlasmaControl/DESC#512]
some of our example equilibria are not consistent with a right-handed coordinate system (SOLOVEV, DSHAPE are two), because they were made with an old input file before we changed them to be right handed (for example the SOLOVEV input file is positive iota but SOLOVEV_output.h5 has a negative iota)

**Comment by rahulgaur104** [comment]
If all we need is to generate a set of new files to close this PR, I can do it.

I would have to regenerate the equilibria in desc/examples and desc/tests. 

Do we also want to regenerate the VMEC files corresponding to the DESC equilibria in desc/tests?
