### ISSUE TITLE
Utility for rescaling equilibria to given major radius and field strength

### ISSUE THREAD

**Issue by f0uriest** [PlasmaControl/DESC#526]
It's common in publications to compare equilibria after re-scaling them to the same major radius and field strength. It would be nice to have a utility to do this automatically.

I think it's fairly straightforward. If we define 2 scale factors:

$c_R = R_{0, desired} / R_{0}$

$c_B = B_{desired} / B$

then we should just have to multiply `R_lmn` and `Z_lmn` by $c_R$, and multiply `Psi` by $c_B c_R^2$.

$J \times B \sim \Psi^2$ so to preserve force balance and beta, we'd also need to multiply $\nabla p$ by $c_B^2c_R^4$, which works out to multiplying `pressure` by $c_B^2c_R^5$ (the extra factor of $c_R$ is due to the $\nabla$ operator, which goes like $1/R$). For temperature and density its trickier since they can vary independently but a simple one would just be to multiply both by the square root.

For fixed current we'd also need to multiply `current` by $c_R c_B$ (I think, based on $I = \int B \cdot dl$)

**Comment by dpanici** [comment]
http://arxiv.org/abs/2106.00716
section 3 of this paper talks about scaling volume and magnetic field strength

**Comment by f0uriest** [comment]
@pkim1818

**Comment by ddudt** [comment]
Correction to the pressure scaling from force balance:

$B \sim c_B$

$J = \nabla \times B \sim \frac{B}{R} \sim \frac{c_B}{c_R}$

$\nabla p = J \times B \sim \frac{c_B^2}{c_R}$

$p \sim R \nabla p \sim c_B^2$

So the pressure profile actually has no dependence on the major radius scaling $c_R$.
