### ISSUE TITLE
Create surface with specified shape parameters

### ISSUE THREAD

**Issue by f0uriest** [PlasmaControl/DESC#542]
Similar to the model we have for approximately QI surfaces, it would be neat to have a simple option for creating a surface based on simple scalar shape parameters:

- [ ] Major radius
- [ ] minor radius / aspect ratio
- [ ] elongation
- [ ] triangularity
- [ ] "twist" (something with n=1)?
- [ ] torsion

**Comment by dpanici** [comment]
Some code I have from a long time ago for making arbitrary 2D shapes, we could repurpose this:

```python
import numpy as np
from matplotlib import pyplot as plt
from ipywidgets import interact
# https://iopscience.iop.org/article/10.1088/0741-3335/55/9/095009/pdf
# Luce 2013

@interact(R0=(0.75,1.5),a=(0.25,1),delta=(-0.5,1.0),xi=(-0.5,0.5),kappa=(-0.5,2.5))
def plasma_XS(R0,a,delta,xi,kappa):
    theta = np.linspace(0,2*np.pi,50)
    R = R0 + a*np.cos(theta + delta*np.sin(theta)-xi*np.sin(2*theta))
    Z = kappa*a*np.sin(theta + xi*np.sin(2*theta))
    plt.plot(R,Z)
    plt.ylim([-kappa*a- 0.1,kappa*a+0.1])
    plt.xlim([R0-a-0.1,R0+a+0.1])
    plt.scatter(R0,0)
    plt.xlabel('R')
    plt.ylabel('Z')
    return None
```

**Comment by rahulgaur104** [comment]
That's a modified Miller parametrization. We can easily take that and do

R = Rcos(phi) - Zsin(phi)
Z = Rsin(phi) + Zcos(phi)

to add a rigid poloidal rotation at we move in phi.
