### ISSUE TITLE
Improve Coil discretization in Biot-Savart Law

### ISSUE THREAD

**Issue by dpanici** [PlasmaControl/DESC#602]
For coils which we know the curvature of (so any coil but the `XYZCoil` which does not necessarily have an accurate curvature), discretizing the coil curves by shifting the line segments along the normal to the curve can double the order of accuracy, could be useful to investigate and implement:

https://www.osti.gov/pages/servlets/purl/1817216

**Comment by f0uriest** [comment]
Caoxiang also showed that using the actual tangents to the curve instead of the linear piecewise linear approximation also helps a lot, and would work for splines as well since it only requires first derivatives (offsetting the points is based on the local curvature which is higher order)

**Comment by dpanici** [comment]
What paper is that from? That sounds like a better way for sure

**Comment by f0uriest** [comment]
It wasn't published afaik, but it was in a presentation in the Spectaculars meeting, I'll send it over.
