### ISSUE TITLE
Elongation returns NaN for circular cross section

### ISSUE THREAD

**Issue by f0uriest** [PlasmaControl/DESC#603]
For circular cross sections (like our default surface and equilibrium starting points), the calculation of elongation returns NaN instead of 1

eg
```python
eq = Equilibrium()
eq.compute("a_major/a_minor")["a_major/a_minor"]
```

I suspect its a numerical issue from taking sqrt of a subtraction that ends up being close to zero. Definitely needs to be fixed, since a circular cross section is a common starting point for optimization.

**Comment by ddudt** [comment]
Resolved by #618.
