### ISSUE TITLE
Use Diffrax for field line integration

### ISSUE THREAD

**Issue by ddudt** [PlasmaControl/DESC#609]
When `field_line_integrate` is used with a `MagneticField` with `extrap=False`, the integration blows up if the field line leaves the pre-defined domain. In these cases, `MagneticField.compute_magnetic_field` returns `NaN` and the integration should stop. 

A possible resolution is to use the package [Diffrax](https://github.com/patrick-kidger/diffrax) for the integration. This would allow us to create an event to stop the integration when the magnetic field is no longer defined.

**Comment by dpanici** [comment]
Just make current ODEint RHS function return 0 if outside specified domain @dpanici

**Comment by dpanici** [comment]
`jax.experimental.odeint` is deprecated, so we need to move on anyways
