### ISSUE TITLE
Glossary of variable names / plotting keys

### ISSUE THREAD

**Issue by f0uriest** [PlasmaControl/DESC#61]
It would be useful if we had a big list of the different physics variables in the code (ie, the output of all the `compute` functions) that had the variable/key name, and a physical description of what it is (and maybe the tex format as well). This would help people both with adding new things to the code, but also with knowing what sorts of things can be plotted, and what sorts of variables are available for analysis

**Comment by ddudt** [comment]
Yes I can make that list.  I was also thinking of re-working the plotting `_compute` method to only handle entries included in that list (things we directly calculate in `compute_funs.py`).  The current design to dynamically figure out the desired value with generic operations is neat, but it rarely gets used and the logic is difficult to maintain for more complicated values, such as `|(B*grad)B|`.

**Comment by f0uriest** [comment]
Yeah I think that makes sense.
