### ISSUE TITLE
github actions out of memory

### ISSUE THREAD

**Issue by unalmis** [PlasmaControl/DESC#617]
Having problems with `tests/test_perturbations.py::test_optimal_perturb` getting canceled. Maybe worth to look into https://github.com/pierotofy/set-swap-space

**Comment by dpanici** [comment]
Is it just on the magnetic axis PR? I have not seen it on any of my other PRs

**Comment by unalmis** [comment]
Yes. The only relevant change in that PR is that `.test_durations` was updated to try and fix this, but that change seems to have moved the out of memory problem to a different test.
