### ISSUE TITLE
Update Plot Legend/Label Functionality

### ISSUE THREAD

**Issue by ddudt** [PlasmaControl/DESC#629]
The following plotting functions are documented to say they support adding a legend by passing the kwarg `label`, but do not actually have it implemented: 
- `plot_1d`
- `plot_fsa`
- `plot_surfaces`

**Comment by dpanici** [comment]
I have definitely used this before... I will check my scripts that use this and see if they still work

**Comment by dpanici** [comment]
This is expected behavior: you should just call `ax.legend()` afterwards to make the legend

What we could do is create the legend whenever label is supplied, then have it just check for an existing legend and update it if it exists

**Comment by f0uriest** [comment]
Resolved by #751
