### ISSUE TITLE
Check NCSX input and output file for consistency

### ISSUE THREAD

**Issue by dpanici** [PlasmaControl/DESC#677]
Force error is worse now when running input file as it is (but inverting iota helps somehow?) compared to the ncsx_output.h5

**Comment by f0uriest** [comment]
ARIES-CS also seems wrong, it should be major radius 7.75 m, minor radius 1.7, 5.7 T on axis, but we have more like 1.4 m major radius, 0.32m minor radius, 1.5 T on axis

**Comment by rahulgaur104** [comment]
Here's [Google Drive zip file](https://drive.google.com/file/d/1f89m_UUtQQ_7DyMDQWOb7f2FRDHKe_qa/view?usp=sharing) containing all the new, recalculated equilibria in desc/examples.

I don't know if this is relevant to this issue but I can't successfully re-run the desc/tests/LandremanPaul_QA and QH equilibria with the master branch. I get the following error:` /desc/equilibrium/coords.py:443: UserWarning: WARNING: Flux surfaces are no longer nested`

**Comment by dpanici** [comment]
Also check the inputs/outputs for hte reactor scale equilibria in `tests/inputs`
