### ISSUE TITLE
make sure Grid sorting is transparent

### ISSUE THREAD

**Issue by dpanici** [PlasmaControl/DESC#678]
Grid will sort the nodes by `zeta`, which when `iota` is negative and you are passing in coordinates along a field line, can actually flip the order of the nodes you've just passed in, resulting in the new nodes having a decreasing `theta` instead of an increasing `theta`, for example. 

We should make this sorting clear/throw a warning when this happens to make it more transparent

**Comment by f0uriest** [comment]
The confusion mostly occurs when creating a custom `Grid`, and in that case I think we can just have `sort` default to false. The only reason we sort things is so they're aligned correctly for doing an FFT, but with a custom grid its very unlikely that the other requirements for an fft would be met (ie equal spacing, same rho/theta at each zeta) so it's probably not worth it for that case.
