### ISSUE TITLE
Make Coil Representation work better with interpolation methods

### ISSUE THREAD

**Issue by dpanici** [PlasmaControl/DESC#682]
Currently, XYZCoils with a `cubic2` spline interpolation will return NaN, maybe we do not need to close the curve when passing points to the interpolation algorithms

**Comment by f0uriest** [comment]
I think as long as you pass period=2pi when you call interpolate that should treat the curve as if it's closed without having to give the endpoint (and if you do give the endpoint you might end up dividing by zero)
