### ISSUE TITLE
Small differences when quantities are evaluated directly vs inside an objective

### ISSUE THREAD

**Issue by landreman** [PlasmaControl/DESC#683]
Hi, I might be doing something wrong, but I'm observing slight differences when computing quantities directly with `eq.compute()` compared to the values computed inside objective functions. Here's one example script:
~~~~py
import desc.io
from desc.grid import QuadratureGrid
from desc.objectives import ObjectiveFunction, MercierStability

filename = "DESC/tests/inputs/iotest_HELIOTRON.h5"
eq = desc.io.load(filename)
eq = eq[-1]

grid = QuadratureGrid(
    L=eq.L,
    M=eq.M,
    N=eq.N,
    NFP=eq.NFP,
)

data = eq.compute(["D_Mercier"], grid=grid)
print("D_Mercier in test:   ", grid.compress(data["D_Mercier"]))
print("grid in test:   ", grid)

obj = ObjectiveFunction(MercierStability(grid=grid, eq=eq))
obj.build()
scalar_objective = obj.compute_scalar(obj.x(eq))
~~~~
Then in `desc/objectives/_stability.py` I add `import jax.debug` at the top, then insert the following at line 189, in `MercierStability.compute()`:
~~~~py
jax.debug.print("D_Mercier in compute: {x}", x=constants["transforms"]["grid"].compress(data["D_Mercier"]))
jax.debug.print("grid in compute: {x}", x=constants["transforms"]["grid"])
~~~~
Output using master on my macbook:
~~~~
DESC version 0.10.0+115.gda715883.dirty,using JAX backend, jax version=0.4.1, jaxlib version=0.4.1, dtype=float64
Using device: CPU, with 4.77 GB available memory
D_Mercier in test:    [-24.2892347   -2.04850931  -0.40570364  -0.03894058   0.06946172   0.0659152    0.05899593   0.06847176  -0.20032184  -0.87951217]
grid in test:    QuadratureGrid at 0x12a51c8b0 (L=9, M=14, N=3, NFP=19.0, sym=False, node_pattern=quad)
Building objective: Mercier Stability
Precomputing transforms
D_Mercier in compute: [-24.29568587  -2.04853021  -0.40570156  -0.03894      0.06946179   0.06591498   0.05899582   0.06847136  -0.20032457  -0.87952281]
grid in compute: QuadratureGrid at 0x13ebf6a70 (L=9, M=14, N=3, NFP=19.0, sym=False, node_pattern=quad)
~~~~
It looks like the grids for the 2 computations are the same (up to memory id), but the values of `D_Mercier` differ starting in the 4th-6th significant digit, which is larger than I'd expect from roundoff error for dtype float64. Any idea why the two methods of computing the same quantity yield these different values?

**Comment by ddudt** [comment]
My guess is that this might be due to JIT-compilation, although I'm surprised it would make that noticeable of a difference. The objective functions are JIT-compiled by default, while `eq.compute()` is not. 

Can you try changing your second to last line to: `obj.build(use_jit=False)` and re-testing? That will at least help determine if JIT is part of the issue.

**Comment by f0uriest** [comment]
Yeah, it's definitely larger difference that we should see from just compilation, I think the actual source of the discrepancy is here:

https://github.com/PlasmaControl/DESC/blob/9f31227d3f8fafe11002d2ff603cc15ffcaa6b2c/desc/equilibrium/equilibrium.py#L768

In `eq.compute` we do some extra logic to ensure things are computed on the "correct" grids (ie, make sure we get accurate volume and surface averages for things that require them). This was done to ensure that stuff like computing `iota` at a single point worked correctly. 

To be conservative we generally oversample the grid resolution by ~2 to account for nonlinearity and aliasing. If you change your `QuadratureGrid` to have `M=eq.M_grid`, `N=eq.N_grid` I get the same values using both methods, regardless of any compilation.

**Comment by landreman** [comment]
Got it, makes sense now, and that fixes it on my end too. Thanks!
