### ISSUE TITLE
Option to constrain toroidal current density

### ISSUE THREAD

**Issue by ddudt** [PlasmaControl/DESC#69]
Presently we only allow the rotational transform profile to be constrained.  We should add an option to alternatively constrain the toroidal current density, and compute the rotational transform that is consistent with that current profile.  

References for how this is implemented in VMEC:
https://reader.elsevier.com/reader/sd/pii/002199918690197X?token=4F909F2C9E78841E7261ACF05D8C5B35C5D735D8962559C084108368C75831501C94899987F7267AF2C3B21B44722ACC&originRegion=us-east-1&originCreation=20210420152412
https://github.com/jonathanschilling/educational_VMEC/blob/educational_VMEC/src/add_fluxes.f90

**Comment by dpanici** [comment]
Related to #79
