### ISSUE TITLE
When loading in VMEC input file, use ensure_positive_jacobian and set check orientation to false for surface

### ISSUE THREAD

**Issue by dpanici** [PlasmaControl/DESC#713]

**Comment by dpanici** [comment]
Did this also affect if we are running a DESC input file where the boundary has the wrong poloidal angle? should ensure positive jacobian be called in that case as well instead of allowing the surface to change?

**Comment by f0uriest** [comment]
Yes, if the DESC input has the wrong orientation we call `ensure_positive_jacobian` which flips the boundary and iota/current.
