### ISSUE TITLE
Add Example Usage of Compute Utils to docs

### ISSUE THREAD

**Issue by dpanici** [PlasmaControl/DESC#723]
Would be useful to show how to use surface_averages etc in docs for users, as it is easier than them looking at the source and otherwise hey wouldn't even know these utilities exist

**Comment by unalmis** [comment]
Maybe those utility methods should be added to the public api?

Note to self: copy/move the last chunk of this section
https://desc-docs.readthedocs.io/en/stable/notebooks/dev_guide/grid.html#A-common-operation-which-relies-on-node-area:-surface-integrals
to a dev guide on using utility functions in #353

**Comment by dpanici** [comment]
make an `integrals` subfolder in `desc`
