### ISSUE TITLE
LambdaGauge with asymmetric equilibria seems to allow lambda(theta=0,zeta=0) to be nonzero

### ISSUE THREAD

**Issue by dpanici** [PlasmaControl/DESC#731]
![Figure_1](https://github.com/PlasmaControl/DESC/assets/37969854/398fa159-ee07-4115-86c3-f34f1606321b)

Seems that with asymmetric equilibria have a non-straight vartheta contour at theta=0, which means that lambda is nonzero there, which our `LambdaGauge` condition (I thought) should address

**Comment by f0uriest** [comment]
These look like they're not stellarator symmetric, so we wouldn't expect that theta itself is straight.
