### ISSUE TITLE
Use "scan trick" to reduce compilation times for loops over functions

### ISSUE THREAD

**Issue by f0uriest** [PlasmaControl/DESC#756]
Something like https://github.com/patrick-kidger/equinox/blob/6846a2b86ff9f049ea332da543ae0b73b04daf52/equinox/internal/_misc.py#L49

**Comment by rahulgaur104** [comment]
I use it [here](https://github.com/PlasmaControl/DESC/blob/47b3d5fadf359cbacdf324fe8dc5729f1609e712/desc/compute/_stability.py#L689C1-L689C82)

Can you give me some examples where we can we use this in DESC?

**Comment by f0uriest** [comment]
That looks more like a regular scan of a function over an array. The scan trick I was referring to combines scan + select to apply a sequence of functions to a given input like `f1(f2(f3(x)))` without having to unroll the loop which is slow in jax. The main place I was thinking of using it is the logic in `desc.compute.compute` where we loop over dependencies to compute stuff, but I'm not sure it will work there since the outputs can be difference sizes.

**Comment by dpanici** [comment]
tested in #1147 and too slow/wasteful
