### ISSUE TITLE
Better tutorials

### ISSUE THREAD

**Issue by f0uriest** [PlasmaControl/DESC#765]
Proposed re-organization:

- [x] Basic equilibrium
  - Running from VMEC input on command line or script
  - Loading surface from VMEC, running in script
  - Creating surface, profiles, using automatic continuation
- [x] Advanced equilibrium
  - Manual continuation method form input file
  - Step by step continuation method in script
- [x] Using DESC outputs
  - Loading and plotting stuff
  - Saving VMEC output
  - Saving boozmn output  
- [x] Basic optimization
  - Specifying objectives and constraints, basic QS optimization
- [ ] #776
- [x] Multi-objective / constrained optimization
  - Include augmented lagrangian vs proximal
- [ ] #778
- [x] Near Axis constraints w/ optimization
- [ ] #775
- [ ] #779
- [ ] #774
- [ ] #773

A lot of this we already have but it might be in more than one place etc. We should try to combine what we currently call "Examples" and "Tutorials" into one more cohesive thing

**Comment by dpanici** [comment]
I think in one of the tutorials, comparing the result of auglag vs proximal could be good as well
