### ISSUE TITLE
normalize stopping criteria

### ISSUE THREAD

**Issue by ddudt** [PlasmaControl/DESC#797]
Everything we optimize is typically of order unity, except for the pressure (or kinetic) and current profiles. This isn't an issue for the optimization steps where things are already normalized relative to the Jacobian, but it could affect the stopping criteria. Most notably `gtol` can have weird units. We should think of a way to account for the norm of x in the optimizers.

**Comment by dpanici** [comment]
Change ``xtol`` to be the normalized ``x`` instead of the physical unit ``x``
