### ISSUE TITLE
Incompatibility with Python 3.12 

### ISSUE THREAD

**Issue by Survivor7127** [PlasmaControl/DESC#824]
I'm a high school student trying to use DESC for a project, so I'm fairly new to Python, and I was wondering if I could get help with this issue I'm having. I've been trying to download the package using pip on Windows 11, but I keep receiving the ModuleNotFoundError message regarding the import distutils.core function and string. I believe that I tracked down the issue to the versioneer.py file and its reference to distutils rather than the new setuptools used in 3.12. However, it does seem that there is a try/except block within the program that should mitigate this, but I'm still having the issue. Can anyone help me solve this?
<img width="960" alt="2024-01-15" src="https://github.com/PlasmaControl/DESC/assets/149177245/951071f0-ad9d-416d-8b77-63c82247821b">
<img width="960" alt="2024-01-15 (1)" src="https://github.com/PlasmaControl/DESC/assets/149177245/732898a9-387e-470f-b6d0-40c95d2dd9f1">
<img width="960" alt="2024-01-15 (2)" src="https://github.com/PlasmaControl/DESC/assets/149177245/163c6ba7-0c40-416b-bfec-cefa017c3496">
<img width="960" alt="2024-01-15 (3)" src="https://github.com/PlasmaControl/DESC/assets/149177245/800c0095-5fa9-404a-b686-1499d5ddf420">

**Comment by ddudt** [comment]
@Survivor7127 did you find a solution to the issue? If so, please document it here for others to reference in the future. 

Make sure you are using the Windows Subsystem for Linux for your Python environment.
