### ISSUE TITLE
Mirror Ratio objective

### ISSUE THREAD

**Issue by ddudt** [PlasmaControl/DESC#848]
Would be useful to have an objective to target a particular mirror ratio. There is already the `"mirror ratio"` compute quantity, so this is trivial to implement for regular equilibria (can already do it with `GenericObjective`). The other use case is to implement something similar that can work for `OmnigenousField` after PR #535 is merged in.

**Comment by dpanici** [comment]
define in `desc/compute/omnigenity.py` `mirror ratio` for parmaterization `OmnigenousField`
