### ISSUE TITLE
`plot_boundary` with single `phi` value gives empty plot

### ISSUE THREAD

**Issue by f0uriest** [PlasmaControl/DESC#877]
```python
desc.plotting.plot_boundary(desc.examples.get("NCSX"), phi=[np.pi]);
```

![image](https://github.com/PlasmaControl/DESC/assets/22567458/05430f8a-c519-4de4-a327-be4a40250e0f)

**Comment by dpanici** [comment]
The plot_boundary for some reason only indexes `phi[0:-1]` so it will not plot every phi you give it, I noticed this a while back but it was too small to warrant trying to fix
