### ISSUE TITLE
`test_compute_everything` Can fail with differences of order `rtol 1e-10` on Mac versus Linux

### ISSUE THREAD

**Issue by dpanici** [PlasmaControl/DESC#937]
Seems that hardware or software differences between Mac and linux can cause the test compute everything to fail on Mac versus linux, but with very minor differences in actual value (things like abs diff of `1e-8` and relative diff of `1e-10`)

If we are comfortable with this we can leave as is but just wanted to make an issue to make it a known thing, or we could reduce the tolerances (but I would probably prefer to leave them as is)

**Comment by unalmis** [comment]
There's a small chance these differences could vanish if we replace all uses of `jnp.sum(a * b)` with `jnp.dot(a, b)` where it's applicable, e.g. https://github.com/PlasmaControl/DESC/blob/5801ea8238a45b6f6674cc0d2ebe67d9d598242f/desc/compute/_field.py#L2624. This would allow using linear algebra libraries for the computations rather than the ufuncs which I've seen suppress some round off erros on scale 1e-8.

**Comment by unalmis** [comment]
I think you're right then since that is what is advertised. But it's not hard to generate examples where the opposite is true, at least on my machine:
```python
import numpy as np
import jax.numpy as jnp
# from desc.backend import jnp # sets jax precision to higher precision which persists in a notebook environment

a = np.arange(100).reshape(10, 10) * np.array([np.pi], dtype=np.float128)
b = a[0]
truth = np.sum(a * b, axis=1)  # can replace with dot, doesn't matter

# jax can't do float128
a = np.arange(100).reshape(10, 10) * np.array([np.pi])
b = a[0]
mulsum_error = np.linalg.norm(np.array(jnp.sum(a * b, axis=1)) - truth)
dot_error = np.linalg.norm(np.array(jnp.dot(a, b)) - truth)
print(mulsum_error)
print(dot_error)
```
`desc.backend.jnp` will lower the errors, but `jnp.dot` is still less error.

**Comment by f0uriest** [comment]
for me I get
```
mulsum error: 8.524274097196166241e-12
dot error:    7.400826775665169309e-12
```
a bit lower but well within the expected range for floating point rounding error due to different order of operations

(Also note that on most systems `np.float128` is really only 80 bits: https://numpy.org/doc/stable/user/basics.types.html#extended-precision)
