### ISSUE TITLE
`Omnigenity` objective is not reverse-mode differentiable

### ISSUE THREAD

**Issue by ddudt** [PlasmaControl/DESC#943]
The issue seems to arise from the fact that `field_data` needs the value of iota from `eq_data`. If `eq_fixed=True` or the value of iota is otherwise hard-coded, then the objective is compatible with reverse-mode AD. 

If a solution is found, remember to:

- [ ] change the default to `deriv_mode="auto"`
- [ ] add the `Omnigenity` objective to `test_objective_no_nangrad`

**Comment by dpanici** [comment]
Try running with jax debug_nans
