### ISSUE TITLE
have custom `Grid` throw error if spacing or weights is called when it was not passed in

### ISSUE THREAD

**Issue by dpanici** [PlasmaControl/DESC#981]

**Comment by unalmis** [comment]
The idea is that, by default we should assign uniform spacing / uniform weights if the user doesn't pass them in. While we can compute the weights to be uniform automatically, it is not possible to compute uniform spacing without additional information. To get uniform spacing you would need to do: https://github.com/PlasmaControl/DESC/blob/b10070e82eb059cf59fbc6621bb4636e16285df9/desc/equilibrium/coords.py#L318 which requires knowing the number of unique surfaces etc. Had I not explicitly passed in the surface then the computation would be incorrect, so we should throw an error unless spacing is passed in explicitly.

**Comment by unalmis** [comment]
And then also delete this chunk, since it is an identity operation for the non-custom grids anyway, and we shouldn't modify spacing if it is passed in by the user.
https://github.com/PlasmaControl/DESC/blob/5801ea8238a45b6f6674cc0d2ebe67d9d598242f/desc/grid.py#L174
