### ISSUE TITLE
Make naming of grids among objectives more uniform

### ISSUE THREAD

**Issue by dpanici** [PlasmaControl/DESC#997]
`VacuumBoundaryError` and `BoundaryError`both have need of an `eval_grid` and `source_grid` yet the former uses `grid` as the kwarg for this while the latter uses `eval_grid`, making these uniform would be nice

**Comment by felicia22** [comment]
Can I be assigned to this issue? I can change VacuumBoundaryError to also use eval_grid

**Comment by dpanici** [comment]
Sure!
